### ISSUE TITLE
Socket.io thread doesn't kill

### ISSUE THREAD

**Issue by tolgay007** [nkzawa/socket.io-client.java#104]
When  I call the mainActivity.finish() the socket.io thread is still works and connected to server.How can I prevent this ?

**Comment by nkzawa** [comment]
You should just call `socket.disconnect()` on all sockets.

**Comment by tolgay007** [comment]
If i call disconnect and close the app then run the app again the on
connect method calling twice

13 Şubat 2015 Cuma tarihinde, Naoyuki Kanezawa <notifications@github.com>
yazdı:

**Comment by nkzawa** [comment]
It sounds a different issue, anyway can you post your code?

**Comment by MadScientistUA** [comment]
It seems i have same issue. When i close activity and then start it again i have two EVENT_CONNECT, and every time when i do that again EVENT_CONNECT calls one time more. Here is my code
```
@Override
    protected void onPause() {
        super.onPause();
        socket.disconnect();
    }

    @Override
    protected void onResume() {
        super.onResume();
        if(socket!=null)
            socket.connect();
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:  // I close activity here
                finish();
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }

    // this method calling from onCreate
    void Socket() throws URISyntaxException {  
        socket = IO.socket(uri);
        socket.on(Socket.EVENT_CONNECT, new Emitter.Listener(){
            @Override
            public void call(Object... args) {
                Log.wtf("","EVENT_CONNECT");
                socket.emit("load", 1);
            }
        });
        Log.wtf("","after connect");
        socket.connect();
    }
```
Here are logs
```
after connect
EVENT_CONNECT
after connect
EVENT_CONNECT
EVENT_CONNECT
after connect
EVENT_CONNECT
EVENT_CONNECT
EVENT_CONNECT
...
```

**Comment by nkzawa** [comment]
@MadScientistUA That is because the socket listens `EVENT_CONNECT` event again and again.
`IO.socket(uri)` returns a cached socket, so you must ensure to listen an event only once in such a way as to remove old listeners when disconnecting.

**Comment by tolgay007** [comment]
I had faced same issue with @MadScientistUA with same code.Then i closed
the all socket listeners after disconnect.Problem resolved.But i think you
have to automaticly close all socket listeners when activiy finishes.

15 Şubat 2015 Pazar tarihinde, Naoyuki Kanezawa <notifications@github.com>
yazdı:

**Comment by nkzawa** [comment]
@tolgay007 thanks for your suggestion, but I have no thought to do that for now because I think the library should not have special features only for Android. Additionally, in some cases, you would not like to automatically close sockets on activity finish.

**Comment by nkzawa** [comment]
I think we can close this issue now. Feel free to reopen if you still have the problem.

**Comment by naartjie** [comment]
@nkzawa 

I have an app which only uses socket.io for the logged in part of the app. So when the user logs out I want to disconnect the client socket from the server completely.

Considering the socket is listening to many events, will this work:
```java
socket.disconnect()
socket.off("connect")
```
or do I need to `socket.off(...)` all the other events I am listening to as well?

**Comment by nkzawa** [comment]
@naartjie Generally, I thinks it's better to remove all listeners when you don't need them any more.

**Comment by naartjie** [comment]
BTW, I just wanted to update here, that the problem I was describing (probably not related to OP's one), is described in #132, together with the solution.
