### ISSUE TITLE
JWT authorization

### ISSUE THREAD

**Issue by emce** [nkzawa/socket.io-client.java#105]
Is it possible to use it with Java client?

**Comment by nkzawa** [comment]
Sorry for the delay. Unfortunately I'm not familiar with JWT :(

**Comment by hugolm84** [comment]
Perhaps late reply, but I'm using JWT tokens as follows:

Android:    

    mSocket = IO.socket(url);
    mSocket.io().on(Manager.EVENT_TRANSPORT, new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                Transport transport = (Transport) args[0];
                transport.on(Transport.EVENT_REQUEST_HEADERS, new Emitter.Listener() {
                    @Override
                    public void call(Object... args) {
                        @SuppressWarnings("unchecked")
                        Map<String, String> headers = (Map<String, String>) args[0];
                        headers.put("authorization", "Bearer " + token);
                    }
                });
            }
        });

NodeJS:

    var self = module.exports = {
        io: function(server) {
            var io = socketio.listen(server);
            // Requires Header Authorization: Bearer TOKEN
            io.use(socketioJwt.authorize({
                secret: jwt_secret,
                handshake: true
            }));

            io.on('connection', function(socket){
                .....
            });
        }
    };

**Comment by emce** [comment]
Great! Thanks for tip!

**Comment by nkzawa** [comment]
Looks the problem was solved, thx @hugolm84.

**Comment by neilyoung** [comment]
@hugolm84 Really long time ago, but do you recall, what socket.io-client-java version you were using? I'm using `implementation('io.socket:socket.io-client:1.0.0')` and the Manager.EVENT_TRANSPORT callback is not invoked.
