### ISSUE TITLE
Does the server can receive an ack from the client ?

### ISSUE THREAD

**Issue by dimitrilahaye** [nkzawa/socket.io-client.java#114]
Hello !
I know how the server can send an ack to the client, and how the client can read it. But I don't know if the server can receive an ack from the client (eg. the server sends datas to the client and I would the server receive a confirmation of the reception by the client).

Am I clear ?

**Comment by nkzawa** [comment]
Yes, you can do like:

```java
socket.on("foo", new Emitter.Listener() {
  @Override
  public void call(Object... args) {
    Ack ack = (Ack) args[args.length - 1];
    ack.call();
  }
});
```

**Comment by dimitrilahaye** [comment]
Thanks for this answer :) And how does the client send the ack to the
server ? 

Le 2015-03-07 15:00, Naoyuki Kanezawa a écrit : 

> Yes, you can do like: 
> 
> socket.on("foo", new Emitter.Listener() {
> @Override
> public void call(Object... args) {
> Ack ack = (Ack) args[args.length - 1];
> ack.call();
> }
> });
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1]
https://github.com/nkzawa/socket.io-client.java/issues/114#issuecomment-77690343

**Comment by dimitrilahaye** [comment]
So if I understand, I could do this ?

```java
Data date = new Date();
socket.on("foo", new Emitter.Listener() {
  @Override
  public void call(Object... args) {
    Ack ack = "Data received by client on" + date;
    ack.call();
  }
});
```

**Comment by nkzawa** [comment]
No, if you'd like to send data with ack, it should be like:

socket.on("foo", new Emitter.Listener() {
  @Override
  public void call(Object... args) {
    Ack ack = (Ack) args[args.length - 1];
    ack.call("Data received by client on" + new Date);
  }
});

**Comment by dimitrilahaye** [comment]
Thanks a lot :-D
