### ISSUE TITLE
client not upgrading to websocket when hitting haproxy(loadbalancer) in front of two socketio servers

### ISSUE THREAD

**Issue by vishal-kedia** [nkzawa/socket.io-client.java#115]
I have two socketio servers behind haproxy, and for the purpose of stickiness i am inserting the cookie at haproxy, to identify the server from which response came from. Now the problem is, when i do so using the code below, my connection is not getting upgraded to 'websocket', i tried to debug the issue and realized that 'transport' event is only emitted in 'setTransport' method in engineio socket class, and not in the 'createTransport' method, (in short during probe 'transport' event is not emitted, leading to websocket handshake request going on different socketio server than where the client is already connected using xhrpolling). 

I was wondering if there is some other work around this issue, or the problem is genuine. Plz help out. Thanks in advance.

 

```
final StringBuffer buf = new StringBuffer();
socket.io().on(Manager.EVENT_TRANSPORT, new Emitter.Listener() {
    @Override
    public void call(Object... args) {
        final Transport transport = (Transport)args[0];
        
        if(transport.name.equalsIgnoreCase(WebSocket.NAME)){
        	transport.once(Transport.EVENT_REQUEST_HEADERS, new Emitter.Listener() {
        		@Override
                public void call(Object... args) {
                    @SuppressWarnings("unchecked")
                    Map<String, String> headers = (Map<String, String>)args[0];
                    if(buf.length()!=0){
                    	headers.put("Cookie", buf.toString());
                    }
                }
        	});
        }
        if(transport.name.equalsIgnoreCase(PollingXHR.NAME)){
            transport.once(Transport.EVENT_RESPONSE_HEADERS,
					new Emitter.Listener() {
						@Override
						public void call(Object... args) {
							@SuppressWarnings("unchecked")
							Map<String, String> headers = (Map<String, String>) args[0];
							String cookie = null;
							if (headers.containsKey("Set-Cookie") && headers.get("Set-Cookie").contains("SERVERID")) {
								cookie = headers.get("Set-Cookie").split(";")[0];
							}
							if (cookie != null) {
								final String stickyCookie = cookie;
								if(buf.length()==0){
									buf.append(stickyCookie);
								}
								transport.on(
										Transport.EVENT_REQUEST_HEADERS,
										new Emitter.Listener() {
											@Override
											public void call(Object... args) {
												@SuppressWarnings("unchecked")
												Map<String, String> headers = (Map<String, String>) args[0];
												// set header												
												headers.put("Cookie", stickyCookie);
											}
										});
							}
						}
					});
        }            
    }
});
```

**Comment by nkzawa** [comment]
You can use url query parameters instead of cookie.

See https://github.com/Automattic/socket.io-client/issues/775

**Comment by vishal-kedia** [comment]
thanks for the prompt reply ... but i already explored all those options .. as in our case we don't append client specific info .. in the url hence we cant use this technique .... as the hashing is done only for the incoming requests ... using 'sid' is out of option as it goes with the second request ... however i found workaround my problem for now as haproxy provides another balancing algorithm 'source' which direct requests coming from the same 'ip' to the same server ... as it hashes on the source of the request.

however .. it would be nice if there is some events on creation of transports as well .. :)

**Comment by nkzawa** [comment]
I understand, thanks for your explanation. I will change `Manager.EVENT_TRANSPORT` to be fired upon transport creation. I think the event should be like that anyway.

**Comment by adrai** [comment]
any news?

**Comment by adrai** [comment]
fyi, a playground: https://github.com/adrai/socket.io-scaling

**Comment by shuoli84** [comment]
@nkzawa Let's close this as it is already fixed.
