### ISSUE TITLE
Use upcoming OkHttp 2.3 WebSocket feature

### ISSUE THREAD

**Issue by niqo01** [nkzawa/socket.io-client.java#116]
Hello @nkzawa I saw your comment here: square/okhttp/issues/193 . I might have some free time soon and might be able to help. I am very interested to use your library with OkHttp for WebSockets. Have you started some work somewhere?

**Comment by nkzawa** [comment]
Thank you for your offer. I'm not still working on this. See the following PR also, thanks for @b95505017 's help.
 
https://github.com/nkzawa/engine.io-client.java/pull/14

**Comment by nkzawa** [comment]
Fixed on v0.5.0.
