### ISSUE TITLE
Passport headers 

### ISSUE THREAD

**Issue by andershagebakken** [nkzawa/socket.io-client.java#117]
Hi, I previously had issue #100 .

I am so sorry, but I am trying to get this authentication to work. Is it correct that I just add

headers.put("username", "myusername");
headers.put("password", "secretpassword");
? 
It does not authenticate, passport works fine when I do it from my online signin form.
It looks like the username and password does not get sent.

Am I missing something? I am trying to use this library on Android and not in a Java-client, but I assume it works the same way in Android. It compiles and tried to connect at least, but I only get "No session found" in my EVENT_ERROR handler.

Thank you so much in advance

**Comment by nkzawa** [comment]
Can you explain why you set username and password to http headers?
I don't know much about how passport works.

**Comment by andershagebakken** [comment]
Thank you so much for responding. I am trying to authenticate my Android client with my server that uses socket io and passport. This package: https://www.npmjs.com/package/passport.socketio <https://www.npmjs.com/package/passport.socketio>

When I use your library, I get the authorization fail, or no session found error. That is why I was wondering how to get my Android client authenticated in the same way my web client authenticates. In a previous issue I asked you (https://github.com/nkzawa/socket.io-client.java/issues/100 <https://github.com/nkzawa/socket.io-client.java/issues/100>), you told me I could implement it my self my using the code you provided. I thought I had to add the username and password to the header, but that does not seem to work. If that is not correct, do you know how I am supposed to do it?

Thank you so much, and I am sorry for the trouble.

Kind regards,
Anders Hagebakken

**Comment by nkzawa** [comment]
I also don't know much about the details of passport, but I believe cookie is used for authentication, thus you need http headers and can implement it by yourself. I'm afraid I can't help more than that.

**Comment by andershagebakken** [comment]
Okay, thank you very much. Is there any way I can add cookies using your library?

Kind regards, 
Anders Hagebakken

**Comment by nkzawa** [comment]
You use http headers for that.

`headers.put("Cookie", "key=value");`

**Comment by ProductOfAmerica** [comment]
@nkzawa is there a way to add headers still?
