### ISSUE TITLE
Broadcast Messages

### ISSUE THREAD

**Issue by okanvurdu** [nkzawa/socket.io-client.java#121]
I can't get broadcast messages from my Android client through `on()` method. Is it possible? How can I get server messages (sent with `broadcast.emit()` method) in my client side?

**Comment by nkzawa** [comment]
It's definitely possible. You just should use `on` method for broadcast messages as well.

**Comment by okanvurdu** [comment]
Hi again, I'm trying to sent broadcast messages with `socket.broadcast.emit`method. After I changed my way to `io.sockets.emit` this problem has solved.

Thanks for your help. :+1:

**Comment by AbdulkadirKadari** [comment]
this is my code i don't send message to server please help me


 public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mSocket.on("new message", onNewMessage);
        mSocket.connect();
        if (getArguments() != null) {
            mParam1 = getArguments().getString(ARG_PARAM1);
            mParam2 = getArguments().getString(ARG_PARAM2);
        }
    }
    private Emitter.Listener onNewMessage = new Emitter.Listener() {

         @Override
        public void call(final Object... args) {
             getActivity().runOnUiThread(new Runnable() {
                 @Override
                 public void run() {
                     JSONObject data = (JSONObject) args[0];
                     String username;
                     String message;
                     try {
                         username = data.getString("username");
                         message = data.getString("message");
                         Log.d("GET MESSAGE",data.toString());
                     } catch (JSONException e) {
                         Log.d("GET MESSAGE","ERROR");
                         return;
                     }
                     Message m = new Message(username, message, true);
                     // add the message to view
                     appendMessage(m);
                 }
             });

        }
    };

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View v= inflater.inflate(R.layout.fragment_message, container, false);
        btnSend = (Button) v.findViewById(R.id.btnSend);
        inputMsg = (EditText) v.findViewById(R.id.inputMsg);
        listViewMessages = (ListView) v.findViewById(R.id.list_view_messages);

        btnSend.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {


                JSONObject obj = new JSONObject();
                try {

                    obj.put("message",inputMsg.getText().toString().trim());
                    obj.put("username","sanjay".trim());
                   // mSocket.send(obj);
                    mSocket.emit("new message", obj);
                    Log.d("SEND MESSAGE",obj.toString());

                    Message m = new Message("sanjay", inputMsg.getText().toString(), true);
                    appendMessage(m);
                    inputMsg.setText("");

                } catch (JSONException e) {
                    Log.d("SEND MESSAGE","ERROR");
                    e.printStackTrace();
                }




                   // Message m = new Message("Me", inputMsg.getText().toString(), true);

                    // Appending the message to chat list
                   // appendMessage(m);





            }
        });
        listMessages = new ArrayList<Message>();

        adapter = new MessagesListAdapter(getActivity(), listMessages);
        listViewMessages.setAdapter(adapter);


        return  v;
    }

    // TODO: Rename method, update argument and hook method into UI event
    public void onButtonPressed(Uri uri) {
        if (mListener != null) {
            mListener.onFragmentInteraction(uri);
        }
    }
    private Socket mSocket;
    {
        try {
            mSocket = IO.socket("http://chat.socket.io");
            Log.d("CONECTION","http://chat.socket.io");
        } catch (URISyntaxException e) {
            Log.d("CONECTION","ERROR");
        }
    }


    @Override
    public void onAttach(Activity activity) {
        super.onAttach(activity);
        try {
            mListener = (OnFragmentInteractionListener) activity;
        } catch (ClassCastException e) {
           // throw new ClassCastException(activity.toString()
                 //   + " must implement OnFragmentInteractionListener");
        }
    }


    private void appendMessage(final Message m) {
        getActivity().runOnUiThread(new Runnable() {

            @Override
            public void run() {
                listMessages.add(m);

                adapter.notifyDataSetChanged();

                // Playing device's notification
                //   playBeep();
            }
        });
    }
    @Override
    public void onDetach() {
        super.onDetach();
        mListener = null;
    }

    /**
     * This interface must be implemented by activities that contain this
     * fragment to allow an interaction in this fragment to be communicated
     * to the activity and potentially other fragments contained in that
     * activity.
     * <p/>
     * See the Android Training lesson <a href=
     * "http://developer.android.com/training/basics/fragments/communicating.html"
     * >Communicating with Other Fragments</a> for more information.
     */
    public interface OnFragmentInteractionListener {
        // TODO: Update argument type and name
        public void onFragmentInteraction(Uri uri);
    }

    @Override
    public void onDestroy() {

        mSocket.disconnect();
        mSocket.off("new message", onNewMessage);
        super.onDestroy();
    }
}

**Comment by shuoli84** [comment]
@nkzawa @okanvurdu Let's close it as it is not an issue anymore.
