### ISSUE TITLE
Use WebSocket transport all times?

### ISSUE THREAD

**Issue by niqo01** [nkzawa/socket.io-client.java#124]
It make sense for me that Javascript clients fallback to different transports when WebSocket is not supported, like by a browser for example.
But I was wondering why and when would the client fallback from Websocket to Polling in Java? Why not using Websocket all the time?

**Comment by nkzawa** [comment]
That is because even if websocket is available, it doesn't mean you always be able to connect to server using websocket by some reasons.
Please see the doc of engine.io for the details. https://github.com/Automattic/engine.io#goals
