### ISSUE TITLE
Each time connecting socket after disconnects causes incremental instance in socket stack.

### ISSUE THREAD

**Issue by kumarkalluri** [nkzawa/socket.io-client.java#128]
Each time connecting socket after disconnects causes incremental instance in socket stack.

STR 
  - Disconnect socket when app in pause state. 
  - Connect the socket when app comes to foreground state(Resume). Here we can observe connecting socket to server two times . if you do above these steps, observes connecting socket 3 times... disconnecting also and so on...

**Comment by nkzawa** [comment]
Do you mean another socket is created when a socket reconnects? Can you post your code here?

**Comment by kumarkalluri** [comment]
public class SocketClient  {
    private static final String TAG = "SocketClient";  
    private JSONObject userObj;
    private Socket mSocket;
    {
        try {
            IO.Options opts = new IO.Options();
            opts.forceNew = true;
            opts.reconnection = false;

            mSocket = IO.socket(Constants.DOMAIN_NAME, opts);
        } catch (URISyntaxException e) {
            throw new RuntimeException(e);
        }
    }

    public SocketClient(Context context, JSONObject userObj) {
        this.context = context;
        this.userObj = userObj;
    }

    public synchronized void connect() {    
        mSocket.on(Socket.EVENT_CONNECT, onConnect);
        mSocket.on(Socket.EVENT_DISCONNECT, onDisconnect);
        mSocket.connect();
    }

    public void disconnect() {
        mSocket.disconnect();
    }
    public boolean connected() {
        return mSocket.connected();
    }
    public void emit(final String event, final Object... args) {
        mSocket.emit(event, args);
    }
    private Emitter.Listener onConnect = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            PSLog.d(TAG, "Socket OnConnected" + userObj);
            mSocket.emit(Constants.SOCKET_ADD_USER, userObj);
        }
    };

    private Emitter.Listener onDisconnect = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            PSLog.d(TAG, "Socket onDisconnect");
        }
    };
   }



public class API {

    private static API instance;
    private static SocketClient client;

    private API() {
    }

    public static API getInstance() {
        if (instance == null) {
            instance = new API();
        }
        return instance;
    }

    public static SocketClient getSocketIO() {
        return client;
    }

    public void init(Context context, JSONObject username) {
        client = new SocketClient(context, username);
    }
}

public class MainActivity extends ActionBarActivity {

    SocketClient socket;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        socket = API.getSocketIO();

        if (socket != null ) {


            if(!socket.connected())
            {
                socket.connect();
            }


        } else {

            JSONObject userObj = new JSONObject();
            try {
                userObj.put("user_id", 6);
                userObj.put(Constants.USERNAME, "Gustavo G");
            } catch (JSONException e) {
                e.printStackTrace();
            }

            PSLog.d("", "User Object : " + userObj.toString());

            API.getInstance().init(this, userObj);
            socket = API.getSocketIO();
            // socket.connect();

        }


    }


    @Override
    protected void onPause() {
        super.onPause();
        if (socket != null)
            socket.disconnect();
    }


    @Override
    protected void onResume() {
        super.onResume();
        Log.d("", "on Resume");

        if (socket != null) {
            Log.d("ChatActivity", "socket connected :  " + socket.connected());
            if (!socket.connected()) {

                socket.connect();
            }
        }



    }
}

**Comment by nkzawa** [comment]
It looks this is because event listeners of `EVENT_CONNECT` and `EVENT_DISCONNECT` are set again and again.
What happens if you change `on()` to `once()` like the following?

```java
        mSocket.once(Socket.EVENT_CONNECT, onConnect);
        mSocket.once(Socket.EVENT_DISCONNECT, onDisconnect);
```

**Comment by kumarkalluri** [comment]
It works fine since i'm starting using this library, but this issue occuring from few days. Anyway, I will try this option also, Let you know the result.

**Comment by kumarkalluri** [comment]
Thanks, Now working fine after i changed on() to once().
