### ISSUE TITLE
how to used in client side for get and send message 

### ISSUE THREAD

**Issue by AbdulkadirKadari** [nkzawa/socket.io-client.java#130]
this is my server url where server chat module are present
http://prajas.com/mypiccolo/Chat/
so how to used in client side for get and send message 
like mSocket= IO.socket("http://localhost:80");

i used server HostGator so here which port is used for socket.io
tell me

this is my chat code for server side
https://www.dropbox.com/s/fhq2qgf4tdnthyo/Chat.zip?dl=0

**Comment by nkzawa** [comment]
I can't debug whole your app. Please focus on a specific problem and make clear the point.
If you just don't know how to use the lib, I recommend to go and ask on stackoverflow.
