### ISSUE TITLE
How to fully disconnect from the server?

### ISSUE THREAD

**Issue by naartjie** [nkzawa/socket.io-client.java#132]
Similar to #131, I cannot seem to disconnect from the server, and I need to do this when a user is logged out of the app. When I start a new session I still have the old socket active, and as a result 2 sockets are open to the server.

So my question: how do I disconnect from the server, so that the `socket.on('disconnect')` event gets a hit on the server? I cannot seem to do it with this client.

My code for the disconnect for the client goes like this:
```java
socket.off();
socket.disconnect();
```

What gives? I have also tried to do `socket.off("event_name")` for all the individual events, but that doesn't seem to work either. I am using version `0.4.2`.

Thanks!!

**Comment by naartjie** [comment]
I have finally solved my problem.

I was connecting with the user's auth token as part of the query string:
```java
Socket socket = IO.socket(REST_HOST + "?auth_token=" + authToken);
```
And on subsequent connections (with a different user and auth token) the socket above would be used again from the cache, and not a new instance created.

So I finally figured out the correct way:
```java
IO.Options opts = new IO.Options();
opts.forceNew = true;
opts.query = "auth_token=" + authToken;
Socket socket = IO.socket(REST_HOST, opts);
```
Doh, that took me a while, but it's working like a charm now. 

@nkzawa would you like a PR to update the readme in case other newcomers also hit a similar problem?

**Comment by nkzawa** [comment]
@naartjie PR is welcome and helpful :D

**Comment by naartjie** [comment]
@nkzawa PR done #142 

Thanks for a great library! :+1:

**Comment by nkzawa** [comment]
Thanks! It was merged.
