### ISSUE TITLE
readme needs updated

### ISSUE THREAD

**Issue by kjkrum** [nkzawa/socket.io-client.java#134]
The Usage section of the readme is completely outdated.  There is no `Socket#on(...)` in the current API.

**Comment by nkzawa** [comment]
It's not true, there is `Socket#on` and outdated at all. Can I ask why did you think so?

**Comment by kjkrum** [comment]
I didn't notice that this library has dependencies.  The first compile error I saw was that `Socket#on(...)` does not exist.  In fact, it is inherited from a class in another library.
