### ISSUE TITLE
How can I send extra data while making Socket.connect ?

### ISSUE THREAD

**Issue by joshimohit** [nkzawa/socket.io-client.java#135]
I have android app and want to send some config data, say login, pwd and some DATA information to server. Based on this info server will accept my connection and set server socket state based on DATA i send.. 
Socket mSocket = IO.socket(mUrl);
// I want to set data before calling connect.
mSocket.connect();

How can I do this ?

**Comment by nkzawa** [comment]
You can use query string.

```
IO.socket("http://host?foo=bar");
```
