### ISSUE TITLE
Version of Java_Websocket to use

### ISSUE THREAD

**Issue by sandrum** [nkzawa/socket.io-client.java#137]
I'm trying to use Socket.io and Engine.io with my android device, but I'm not able to connect via ssl because of a missing java class in Java_Websocket, required by Engine.io.  The java file is DefaultSSLWebSocketClientFactory.java and the error is that Android cannot find the missing class DefaultSSLWebSocketClientFactory. This seems to only apply for SSL (wss) connections.  Is there an "appropriate" version of java_websocket on github that works with ssl for socket/engine io?

The reason I ask here is that there IS a version of java_websocket (tootallnate 1.3.0) on the maven (http://mvnrepository.com/artifact/org.java-websocket/Java-WebSocket/1.3.0) repository that seems compatible, but also seems to be different in age to the version of java_websocket (also tootallnate 1.3.0) on github.

**Comment by nkzawa** [comment]
Download java-websocket from Maven central. Anyway I recommend to use maven or gradle to resolve dependencies though.
Regarding SSL, unfortunately, there is an issue: https://github.com/nkzawa/socket.io-client.java/issues/88
