### ISSUE TITLE
why i can't get the getActivity.runOnUiThread?

### ISSUE THREAD

**Issue by armadeas** [nkzawa/socket.io-client.java#138]
I'm create and put this 
private Emitter.Listener onNewMessage = new Emitter.Listener(){
bla bla bla
}
in my app(MainActivity) same as in tutorial at http://socket.io/blog/native-socket-io-and-android/,
but why i have error in getActivity().runOnUiThread(new Runnable() { ?
when i ctrl + space, there is no getActivity

anyone can help me?
it's my first time combine speech to text and socket io

**Comment by armadeas** [comment]
and when i put this in onCreate after mSocket.connect();

        if(mSocket.connected()){
            txtSpeechInput.setText("Connected");
        }else{
            txtSpeechInput.setText("Not Connected");
        }

why it's always not connected?

**Comment by armadeas** [comment]
here the full code of my MainActivity.java
http://pastebin.com/mZn8pPzX

**Comment by armadeas** [comment]
and here the error that show in DDMS
http://pastebin.com/bCCbDW9k

**Comment by joshimohit** [comment]
This is because you are writing getActivity method inside
Emitter.Listener() object, where as getActivity() method is avaiable in
Acitivity class.

Solution: Use <YourActivityName>.this.getActivity() method inside
Emmiter.Listener

e.g.
class MainActivity extends Activity{
//Blah Blah

private Emitter.Listener onNewMessage = new Emitter.Listener(){
bla bla bla

MainActivity.this.getAcitivity().runOnUiThread(new Runnable() { //code}
}


}

**Comment by armadeas** [comment]
Well, i try it crash and i have same error sir,
http://pastebin.com/bCCbDW9k

**Comment by armadeas** [comment]
oh sorry, it's done.

but i have new error.
04-21 15:05:34.137    1722-1722/rpl.speechtotext E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at rpl.speechtotext.MainActivity.addMessage(MainActivity.java:79)
            at rpl.speechtotext.MainActivity.access$100(MainActivity.java:32)
            at rpl.speechtotext.MainActivity$2$1.run(MainActivity.java:113).

here the code at line 79 until 113


private void addMessage(String username, String message){
        try {
            mMessage.add(new Message.Builder(Message.TYPE_MESSAGE).username(username).message(message).build());
            mAdapter.notifyItemInserted(mMessage.size()-1);
        }catch (NullPointerException e){
            e.printStackTrace();

        }
    }

    //Emmit event (Sending data)
    private void attemptSend(){
        if(!mSocket.connected()) return;

        String message = txtSpeechInput.getText().toString().trim();
        if(TextUtils.isEmpty(message)){
            return;
        }

        addMessage(mUsername, message);
        mSocket.emit("new message", message);
    }

    //Listening new message event to receive message
    private Emitter.Listener onNewMessage = new Emitter.Listener() {
        @Override
        public void call(final Object... args) {
            MainActivity.this.runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    JSONObject data = (JSONObject) args[0];
                    String username;
                    String message;
                    try {
                        username = data.getString("username");
                        message = data.getString("message");
                    } catch (JSONException e) {
                        e.printStackTrace();
                        return;
                    }
                    addMessage(username, message);
                }
            });
        }
    };

**Comment by nkzawa** [comment]
Where did you get the error actually on your code?

**Comment by armadeas** [comment]
@nkzawa in addMessage method.

now i change all of my code, 
i use your program for base of my code. (https://github.com/nkzawa/socket.io-android-chat)
i put some code from http://www.androidhive.info/2014/07/android-speech-to-text-tutorial/

There's no error but why method attemptSend() is can't be called?

if you want to see my code, here it is http://pastebin.com/GtcBNP9k
i want to put attemptSend() after line number 202.
But, why it's not working? :(

sorry if my english is bad or wrong.

**Comment by armadeas** [comment]
so it will look like this
switch (requestCode) {
 
            case REQ_CODE_SPEECH_INPUT: {
                if (resultCode == Activity.RESULT_OK && null != data) {
 
                    ArrayList<String> result = data
                            .getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);
                            mInputMessageView.setText(result.get(0));
                            attemptSend()
                            Toast.makeText(getActivity().getApplicationContext(), "YOLO" , Toast.LENGTH_SHORT).show();
                }
                break;
            }
 
        }

**Comment by armadeas** [comment]
i want to input the chat but with voice. 
so first, i press the button, then the google speech input show -> i'm speaking -> then what i say is send to the chat

**Comment by nkzawa** [comment]
Umm, I don't get your problem. Maybe it would be better to ask on stackoverflow.

**Comment by armadeas** [comment]
umm, ok ok.
Thanks sir :D

**Comment by armadeas** [comment]
@nkzawa 
what it is for sir?
 
mInputMessageView.setOnEditorActionListener(new TextView.OnEditorActionListener() {
            @Override
            public boolean onEditorAction(TextView v, int id, KeyEvent event) {
                if (id == R.id.send || id == EditorInfo.IME_NULL) {
                    attemptSend();
                    return true;
                }
                return false;
            }
        });

**Comment by nkzawa** [comment]
@armadeas it's for sending a message when an user pressed a specific key on keyboard.

**Comment by nkzawa** [comment]
It looks we can close the issue now. Feel free to reopen the issue if you still have the problem.
