### ISSUE TITLE
socket.connected() method return false even when socket is connected..?

### ISSUE THREAD

**Issue by joshimohit** [nkzawa/socket.io-client.java#139]
1. mSocket.connect();
2. boolean isConnected = mSocket.connected();

Why do isConnected is false at line 2? However I am still able to emit the data ?

**Comment by nkzawa** [comment]
That's because actually socket is not connected yet. You have to  wait for `EVENT_CONNECT` event.
You can emit a message before connecting because the library buffer your message and send it when the connection is established.

**Comment by WaqasMumtaz** [comment]
What is solution ?

**Comment by pooja1324** [comment]
In android, after mSocket.connect(); listen to EVENT_CONNECT event. After receiving EVENT_CONNECT event, mSocket.connected() will return true.
socket.once(EVENT_CONNECT, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.i(TAG, "call: "+args);
                }
            });

On server side, emit event named "connect" to establish connection

**Comment by enarddpascua** [comment]
This is also occurring to me. I'm getting a false value on `socket.connected` even if I log the `socket` itself and getting a property `connected: true`.

**Comment by darrachequesne** [comment]
For future readers, please see https://socketio.github.io/socket.io-client-java/socket_instance.html#Socket.23connected
