### ISSUE TITLE
Sockets sending no response on Lollipop

### ISSUE THREAD

**Issue by wingoku** [nkzawa/socket.io-client.java#141]
When I try to connect & emit an event on sockets, I don't get any response on lollipop devices. It is working fine on Kitkat devices. What can be the reason for this behavior? Any solution?

**Comment by nkzawa** [comment]
Maybe you are using SSL to connect ? Unfortunately, there's an issue for this.

https://github.com/nkzawa/socket.io-client.java/issues/26

**Comment by shuoli84** [comment]
I tried on android 5.0 and 5.1, it works without any issue. Both http and https. Let's close this. @wingoku @nkzawa

**Comment by nkzawa** [comment]
Closing. Feel free to reopen.

**Comment by localhostEU** [comment]
Android 6.0 (Nexus 5) Same issue, emitting an event and get no response while response from server is being sent.
