### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by MuhammadKamal** [nkzawa/socket.io-client.java#143]
I try to reconnect if the connection timed out what happens it just keep showing endless timeout message
```java
).on(Socket.EVENT_CONNECT_TIMEOUT, new Emitter.Listener() {
                @Override
                public void call(Object... objects) {
                    Log.e("timeout", "true");
                    socket.connect();
                }
            });
```
I commented these lines trying to avoid the connection timeout:
```java
           IO.Options opts = new IO.Options();
            opts.reconnection = true;
            opts.reconnectionDelay = 1000;
            opts.timeout = 10000;
```
Another question does it support SSL because I searched a lot with no use.

**Comment by nkzawa** [comment]
The library has the default timeout value, so if you'd like to disable it, set `-1` like the following.

```java
opts.timeout = -1;
```

And it supports SSL. Please see readme how to set SSL settings.

**Comment by MuhammadKamal** [comment]
Thanks man I appreciate your work.

**Comment by nkzawa** [comment]
Looks the issue was solved. Feel free to reopen the issue if you still have the problem.

**Comment by MuhammadKamal** [comment]
@nkzawa The problem happened again.

**Comment by MuhammadKamal** [comment]
Is it a problem that i'm using engine.io-client-0.4.1.jar?

**Comment by nkzawa** [comment]
Please explain the detail of your problem and how to reproduce it if possible.

**Comment by MuhammadKamal** [comment]
The problem is in the event of EVENT_CONNECT_TIMEOUT it keeps showing this message:
timeout --- true    endlessly
I don't if it's because i'm calling socket.connect(); inside the event or because i'm using 
engine.io-client-0.4.1.jar?
and that's what happens  inside the event:
.on(Socket.EVENT_CONNECT_TIMEOUT, new Emitter.Listener() {
                @Override
                public void call(Object... objects) {
                    Log.e("timeout", "true");
                    socket.connect();
                }
            });

**Comment by nkzawa** [comment]
Did you set `opts.timeout = -1;` ?

**Comment by MuhammadKamal** [comment]
Yes i did.

**Comment by MuhammadKamal** [comment]
IO.Options opts = new IO.Options();
            opts.reconnection = true;
            opts.reconnectionDelay = 1000;
            opts.timeout = -1;
           socket = IO.socket("http://address", opts);

**Comment by nkzawa** [comment]
Ah I'm sorry I was wrong, you can't disable timeout like that. Please try the following.

```java
socket.io().timeout(-1);
```

**Comment by MuhammadKamal** [comment]
how long does it take for the default timeout to happen?

**Comment by nkzawa** [comment]
It disables the timeout.

**Comment by MuhammadKamal** [comment]
ok thanks I know that it disables it i'm asking about if it have a default time or not?

**Comment by nkzawa** [comment]
The default timeout is 20 seconds.

**Comment by MuhammadKamal** [comment]
Ok thanks a lot for now it's working fine i'll let you know it anything shows up i don't know who are you :) but you are doing great.
