### ISSUE TITLE
Offical website is OK but localhost not OK

### ISSUE THREAD

**Issue by wayne1203** [nkzawa/socket.io-client.java#144]
Hi, I just downloaded the android and the chat server demo for internal use.

All setting are default expected the IO.socket in Android changed to
mSocket = IO.socket("http://192.168.123.173:3000");

192.168.123.173 is my IP Address of my computer, firewall turned off already.

But when I click "Join" in android when using chat server in my computer, there are no effect...
Therefore, changed the chat server to "http://chat.socket.io/" , it will sucessfully logged in to the server...

Is it have something wrong in my setting?

Thanks a lot.

**Comment by naresh924** [comment]
I'm facing the same problem. Did you find a solution?

**Comment by nkzawa** [comment]
Are you using https://github.com/nkzawa/socket.io-android-chat ?
Then you have to change 2 lines.

https://github.com/nkzawa/socket.io-android-chat/blob/master/app/src/main/java/com/github/nkzawa/socketio/androidchat/MainFragment.java#L49 https://github.com/nkzawa/socket.io-android-chat/blob/master/app/src/main/java/com/github/nkzawa/socketio/androidchat/LoginActivity.java#L35 .

**Comment by naresh924** [comment]
@nkzawa I'm trying to connect to a local server running socket IO v0.9 from my android client but only reconnect gets triggered repeatedly. However, I'm able to connect to "http://chat.socket.io"
I have added internet and network state permissions in the manifest.
The same server connects from an iOS client.

**Comment by nkzawa** [comment]
@naresh924 Unfortunately, this library is not compatible with socket.io v0.9.

**Comment by wayne1203** [comment]
@nkzawa  Thanks, it's work now~
