### ISSUE TITLE
When Idle for long time, socket gets disconnected but event not received.

### ISSUE THREAD

**Issue by joshimohit** [nkzawa/socket.io-client.java#147]
I am listening to event Socket.EVENT_CONNECT and Socket.EVENT_DISCONNECT in my Android Service. When socket is idle for long time it gets disconnected but EVENT_DISCONNECT is not received. However, if I manually disconnect the socket EVENT_DISCONNECT is received.

**Comment by nkzawa** [comment]
You have to disconnect/reconnect sockets according to Activity lifecycle because socket can't respond to heartbeart check and the connection is lost when the app is in idle state.

**Comment by joshimohit** [comment]
@nkzawa  : I am listening for Push when app is in background. So, I am listening to connect/disconnect events, even when in background. When in longer duration (say after 1 hours), we can see that socket was disconnected (on server), but on client end no disconnect event was received.

**Comment by nkzawa** [comment]
Hmm, thanks for your explanation, yea, It sounds a bug.
I'd like to reproduce the problem, is it easily to do so?

**Comment by MohamedHatem** [comment]
Is there any updates related to this problem ? "on client end no disconnect event was received."

**Comment by joshimohit** [comment]
I haven't received this error since I upgraded to 0.5.1 version.
