### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'void com.github.nkzawa.socketio.client.Ack.call(java.lang.Object[])' on a null object reference

### ISSUE THREAD

**Issue by yanaperhun** [nkzawa/socket.io-client.java#153]
Hi!
I'm using com.github.nkzawa:socket.io-client:0.5.0 library to connect to server. After some requests i am getting 

NullPointerException: Attempt to invoke interface method 'void com.github.nkzawa.socketio.client.Ack.call(java.lang.Object[])' on a null object reference
at com.github.nkzawa.socketio.client.Socket.onack(Socket.java:349)

Can anyone help me? Thanks.

**Comment by nkzawa** [comment]
Can you post a code snippet which I can reproduce the issue if possible?

**Comment by yanaperhun** [comment]
When backend server sends two responses by one request. I understand that it's incorrect server behaviour but i haven't got access to server and my app crashes with fatal exception. Can library throw exception or catch it?

**Comment by nkzawa** [comment]
Fixed on v0.5.1.

**Comment by partikles** [comment]
Guys,
   We have the same error and what does it mean "backend server sends two responses by one request"?
