### ISSUE TITLE
Android: socket.io-client.java version 0.5.0

### ISSUE THREAD

**Issue by najeebullahshah** [nkzawa/socket.io-client.java#154]
I have used the jar of the socket.io-client.java version 0.5.0 in my app using eclipse. After importing related libraries there comes an error when i hover on the package name at top. Following is the error:

"The type com.github.nkzawa.emitter.Emitter cannot be resolved. It is indirectly referenced from required .class files"

Why am i getting this error?

**Comment by joshimohit** [comment]
Emitter class can be found in engine.io java library.

Apart from socket.io (version 0.5.0) java library you would need following
libraries to build your project  successfully:

engine.io - version 0.5.0
okhttp- version 2.3.0
okhttp-ws- version 2.3.0
okio- version 1.3.0

Thanks,
Mohit Joshi

**Comment by najeebullahshah** [comment]
thanks alot. The error is removed after i included the engine.io library.
Also am i getting the Threadpoolexecutor crash on socket.connect() due to the remaining libraries which i didn't included?

**Comment by najeebullahshah** [comment]
Wow Mohit i included the remaining libraries and everything is running fine. You are champ man.

**Comment by shuoli84** [comment]
@naartjie Anyone mind close this issue?

**Comment by najeebullahshah** [comment]
how to close it?

**Comment by naartjie** [comment]
@shuoli84 huh? why me? ;-)

**Comment by najeebullahshah** [comment]
can you please check #157

**Comment by shuoli84** [comment]
@naartjie I must drunk when I at you last time. :P

**Comment by mouryaamit** [comment]
@joshimohit please tell mvn repo for other 4 libs which we need to add.

@nkzawa This should be documented or should be included in socket.io lib as everyone will only add socket.io lib and does not know where the error comes due to missing of other libs

**Comment by nkzawa** [comment]
@mouryaamit I have no thought to do that, since only the recommended way is to use a build automation tool like Maven or Gradle.

**Comment by mouryaamit** [comment]
@nkzawa then you should document them as prerequisite

**Comment by joshimohit** [comment]
It is already documented. I took dependency from : 

http://nkzawa.github.io/socket.io-client.java/dependencies.html

**Comment by nkzawa** [comment]
ah, I didn't know this page lol. Thx, @joshimohit :smile:

**Comment by nkzawa** [comment]
It's a bit old. I will update it later.

**Comment by joshimohit** [comment]
:D :). Also, @nkzawa whoever is working on android, might someday want these libraries to be part of their build system than completely relying on gradle/maven. It will be good if you update it and reference it on installation procedure on home page as well.

**Comment by nkzawa** [comment]
@joshimohit updated the page and add the link to readme. Thanks again :smile:
