### ISSUE TITLE
Fix the slowness websocket transport

### ISSUE THREAD

**Issue by shuoli84** [nkzawa/socket.io-client.java#156]
Hi nkzawa, the websocket client uses a long time to connect to the socketio server, I saw someone encounter this problem too. 
OkHttp 2.4.0 fixed this, could you please release a new version? I opened an issue in engine.io-client project too. :)

**Comment by nkzawa** [comment]
I will release a new version on this weekend.

**Comment by shuoli84** [comment]
That'll be great. Thanks!

**Comment by nkzawa** [comment]
Released as 0.5.1.
