### ISSUE TITLE
How to produce messages with packet type id like 420

### ISSUE THREAD

**Issue by salexwm** [nkzawa/socket.io-client.java#162]
I'm writing android client for a chat.

Connection link is ws://server.com:port/socket.io/?EIO=3&transport=websocket. So i know there is socket.io libs on the server side.

Communication with server looks like that:
to server  420["login", {"token": jwtToken}]
from server 430[{"status":"ok","responseString"}] or 430[{"status":"error","responseString"}] 
to server 420["join", {channel: "default_channel"}]
from server 430[{"status":"ok","responsestring"}]

But my app sending only 42 messages. Not a 420
It works fine on the default chat.socket.io.

So is it posible to send 420 (or 421 etc.) messages and how ?

**Comment by salexwm** [comment]
Found answer by myself.
Library sends 42x messages only if emit method has ACK callback

**Comment by shuoli84** [comment]
@salexwm then pls close this? Since it is not an issue anymore. :)
