### ISSUE TITLE
Socket.connect() very slow

### ISSUE THREAD

**Issue by durunvo** [nkzawa/socket.io-client.java#166]
Im using this library, it is very easy to use. But the problem is that when i try to connect to socket to server using 
socket.connect()
it took more than minute to get response "connect" from server.

Using iOS app connect in no time, when android took more than minutes or sometimes forever. So im pretty sure it is not server's problem.
So im asking if anyone got this problem as well, or how to fix this?

**Comment by nkzawa** [comment]
Is that https://github.com/nkzawa/socket.io-client.java/issues/156 ? What version of the library do you use?

**Comment by shuoli84** [comment]
Should be the same. Let's close it as dup.

**Comment by nkzawa** [comment]
Closing. Feel free to reopen.

**Comment by durunvo** [comment]
sorry for late response,

the problem is i didn't put some code,

                IO.Options opts = new IO.Options();
                opts.transports = new String[]{"websocket"};
                mSocket = IO.socket(SOCKET_SERVER, opts);

now it works fine, thanks for help!!
