### ISSUE TITLE
Cant get any response while running inside AsyncTask

### ISSUE THREAD

**Issue by nabeelpkl** [nkzawa/socket.io-client.java#169]
cant get any response from the server while running this code inside AsyncTask. socket gets disconnected instantly. Is there any order in executing this code. I am new to this. please help

**Comment by nkzawa** [comment]
Can you post your code here? I'd like to know what you are trying to do.

**Comment by nabeelpkl** [comment]
public class SearchSuggestThread extends AsyncTask<String, Void, Void> {
    private final String LOG_TAG = SearchSuggestThread.class.getSimpleName();

    Socket socket;

    @Override
    protected Void doInBackground(final String... params) {

        if (params.length == 0) {
            return null;
        }

//        mResultAdapter.clear();
        try {
            socket = IO.socket("http://119.81.207.20:8087");
            socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {

                @Override
                public void call(Object... args) {
                    socket.emit("echo", params[0]);

                }

            }).on("checking", new Emitter.Listener() {

                @Override
                public void call(Object... args) {
                    JSONArray array = (JSONArray) args[0];
                    Log.d("SearchThread", args[0].toString());
//                            try {
//                                getShopNameFromJson(array);
//                                socket.disconnect();
//                            } catch (JSONException e) {
//                                Log.e(LOG_TAG, e.getMessage(), e);
//                                e.printStackTrace();
//                            }
                }

            }).on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {

                @Override
                public void call(Object... args) {
                }

            });
            socket.connect();
        } catch (URISyntaxException e) {
            Log.e(LOG_TAG, e.getMessage(), e);
            e.printStackTrace();
        } finally {
            socket.disconnect();
        }
        return null;
    }

    @Override
    protected void onPostExecute(Void aVoid) {
        super.onPostExecute(aVoid);
        Log.d("Search Thread","" + "Post execute");
    }
}

**Comment by nkzawa** [comment]
You don't have to use `AsyncTask` or other background threads in this case.
socket.io java client will automatically create new threads if it's required.

btw, you should not call `socket.disconnect();` on the finally clause.
That will stop establishing the connection.

**Comment by nabeelpkl** [comment]
can i execute this in the UI Thread.?. And then where should I call socket.disconnect();

**Comment by nkzawa** [comment]
> can i execute this in the UI Thread.?

yes

> And then where should I call socket.disconnect();

Where you actually need to close the connection.
Your code is the same with the following.

```
socket.connect();
socket.disconnect(); 
```

Please see REAME for the details.

**Comment by nabeelpkl** [comment]
thanks @nkzawa for your great help. :)
