### ISSUE TITLE
The manager will create new connections even when it is in Openning state

### ISSUE THREAD

**Issue by shuoli84** [nkzawa/socket.io-client.java#172]
The js manager code:
``` javascript
if (~this.readyState.indexOf('open')) return this;  // this works for open and openning
```

Our code:
``` java
if(Manager.this.readyState != Manager.ReadyState.OPEN) { // Only works for open
```

**Comment by shuoli84** [comment]
And could you please arrange a new release after this fixed?

**Comment by yanaperhun** [comment]
I faced with the same problem.
Will fixes this problem in the near future?

**Comment by nkzawa** [comment]
Thanks! Fixed on https://github.com/nkzawa/socket.io-client.java/commit/9a385377c54d98719c0682742f2083c18e1ae34a and will release a new version on this weekend.

**Comment by shuoli84** [comment]
Thanks @nkzawa, that'll be great. Will close this once it is released. 

BTW, we are using this lib in production, so I am doing active trouble shooting and trying to clean the issue list. 30+ open issue is bit scary. And you are the one with full knowledge to do this, could you please go through them and close the ones not valid anymore?

**Comment by nkzawa** [comment]
@shuoli84 thanks for you help :smile: I will close them as much as we can.

**Comment by nkzawa** [comment]
Released, thanks again :smiley:

**Comment by shuoli84** [comment]
:+1:
