### ISSUE TITLE
[proposal] Merge engine and socket into one library?

### ISSUE THREAD

**Issue by shuoli84** [nkzawa/socket.io-client.java#173]
I think there is very few (or none) people using engine.io java client separately. Why not merge these two bros together? That will make code contribution and release much easier. 

Correct me if I'm wrong. :)

**Comment by nkzawa** [comment]
I'm not sure how much engine.io is used alone, but think it'd be nice to keep that option so far.

**Comment by shuoli84** [comment]
Well, then we have to pay for each release. And we can deprecate the lib step by step. e.g, first integrate into socket.io-client, then mark the deprecation of engine.io-client. 
I have the gut feeling that engine.io-client is only meaningful when it is used with socket.io for most of us(App developer :)).

**Comment by nkzawa** [comment]
Actually, release cost is not a problem since it's semi-automated.
Engine.io is not only for socket.io. I know several projects and people including I use engine.io, even though not sure how many java version is used.
