### ISSUE TITLE
Why does IO.socket(URI) throw URISyntaxException?

### ISSUE THREAD

**Issue by kjkrum** [nkzawa/socket.io-client.java#174]
It seems like `IO.socket(URI)` should not throw a `URISyntaxException`, since the argument should have already been validated when it was constructed.  If there are additional requirements beyond being a valid URI, it seems like `IO.socket(URI)` should throw something else.

From the compiler's perspective, the reason `IO.socket(URI)` throws `URISyntaxException` is because lines 62-68 of `IO.java` convert the `URI` to a `URL` and then back to a `URI`.  What is the purpose of this conversion?  Would it be possible to eliminate the `throws` clause?

**Comment by nkzawa** [comment]
Fixed to not throw the exception when calling `IO.socket(URI)`, thanks @kjkrum !
