### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by ZhangPeibin** [nkzawa/socket.io-client.java#179]
How can I reconnect when the socket disconnect?

**Comment by shuoli84** [comment]
You can listen event "Disconnect" and call socket.connect() in the handler. 

Note: If the disconnect caused by network error etc, the library will reconnect.

**Comment by nkzawa** [comment]
Yeah, right. Thx, @shuoli84 .

**Comment by shuoli84** [comment]
@ZhangPeibin close this?

**Comment by ZhangPeibin** [comment]
@shuoli84 Thanks !
