### ISSUE TITLE
EventThread.exec() run delay problem?

### ISSUE THREAD

**Issue by durunvo** [nkzawa/socket.io-client.java#182]
Hi, im just wonder that in socket.java line 162 EventThread.exec() sometimes not fire immediately after call emit. This happen frequently. Is there any reason why its doesn't fire immediately?

this is example
![screen shot 2558-07-03 at 4 00 04 pm](https://cloud.githubusercontent.com/assets/5458194/8516591/32dde2ea-23e0-11e5-94b8-754497a8c692.png)
this image above means that i call emit so many times.
![screen shot 2558-07-03 at 4 00 35 pm](https://cloud.githubusercontent.com/assets/5458194/8516549/afe383f4-23df-11e5-9e9f-59a5fa9d9063.png)
and this image means that all the emit acknowledge and socket.on("message") came all at the same time. from the above emit. (you can see the time the time delay)
In fact it should be like emit then socket.on("message") and finally acknowledge

So i have trace through your library and see which lines of code doesn't fire. So i found out it is socket.java line 162 EventThread.exec().

Any suggestion?

**Comment by nkzawa** [comment]
That is because most programs of the library run in the particular thread (EventThread).
There should be a bit delay if you call `emit` from Android UI thread, for example.

**Comment by durunvo** [comment]
So should i call emit from background thread?

**Comment by nkzawa** [comment]
I think you don't need to do anything. Or do you actually have any problems with this behavior?

**Comment by durunvo** [comment]
It came out that background threads are delay to be execute, which is not good because socket should be emit and then receive acknowledgement asap. (At least emit without delay...)

**Comment by nkzawa** [comment]
Unfortunately, it's inevitable. The library tries to send data ASAP, it's just asynchronous behavior.

**Comment by durunvo** [comment]
yes, i understand the point. i can close the issue now cause its not about the library.
