### ISSUE TITLE
get set-cookie head from 'EVENT_RESPONSE_HEADERS' event

### ISSUE THREAD

**Issue by wayne221b** [nkzawa/socket.io-client.java#185]
Hi, i want to save the cookies set by my socket.io server, and my codes are:

```java
socket.io().on(Manager.EVENT_TRANSPORT, new Emitter.Listener() {
    @Override
    public void call(Object... args) {
        Transport transport = (Transport) args[0];
        transport.on(Transport.EVENT_RESPONSE_HEADERS, new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                Map<String, String> headers = (Map<String, String>) args[0];
                // get cookie
                String value = headers.get("Set-Cookie");
            }
        });
    }
});
```
so, it can only get the last "Set-Cookie" header. When my server sets multi cookies, it fails to get them.

Because I'm a new fish, so, can you help me?

**Comment by nkzawa** [comment]
Umm, unfortunately there is no way to get all `Set-Cookie` header values for now. We will address the problem.

**Comment by wayne221b** [comment]
Thanks. In your engine.io-client source code, i find codes as follow
```java
Map<String, String> headers = new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);
Map<String, List<String>> xhrHeaderFields = xhr.getHeaderFields();

if(xhrHeaderFields != null) {
    for (String key : xhrHeaderFields.keySet()) {
        if (key == null) continue;
        headers.put(key, xhr.getHeaderField(key));
    }
}

self.onResponseHeaders(headers);
```
from the `xhrHeaderFields`, i can get all headers in response because it's `Map<String, List<String>>`, but i don't know why you should declare another `Map<String, String> headers`, and lost the `Set-Cookie` headers in the loop followed. 

So i add some codes in your source code to emit another event which return the `xhrHeaderFields`. Now i can save and send all cookies successfully.

Thank you again.

**Comment by nkzawa** [comment]
I created a PR to fix this. https://github.com/nkzawa/engine.io-client.java/pull/24

**Comment by wayne221b** [comment]
Good! I will update in my next app version.

**Comment by nkzawa** [comment]
Fixed version has been released. @wayne221b thanks for your help.
