### ISSUE TITLE
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Exception

### ISSUE THREAD

**Issue by alekperos** [nkzawa/socket.io-client.java#191]
Hi, 

First of all thanks for this client library, it works great, but recently I had an issue with onSocketConnectError event handler. I got this:

`
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Exception
0com.aimdriven.taxiyesdriver.MyLocationFragment$33.callMyLocationFragment.java:1983
1com.github.nkzawa.emitter.Emitter.emitEmitter.java:117
2com.github.nkzawa.socketio.client.Socket.access$601Socket.java:18
3com.github.nkzawa.socketio.client.Socket$5.runSocket.java:166
4com.github.nkzawa.thread.EventThread.execEventThread.java:50
5com.github.nkzawa.socketio.client.Socket.emitSocket.java:162
6com.github.nkzawa.socketio.client.Manager.emitAllManager.java:153
7com.github.nkzawa.socketio.client.Manager.access$600Manager.java:21
8com.github.nkzawa.socketio.client.Manager$1$4$1.runManager.java:310
9com.github.nkzawa.thread.EventThread$2.runEventThread.java:75
10java.util.concurrent.ThreadPoolExecutor.runWorkerThreadPoolExecutor.java:1112
11java.util.concurrent.ThreadPoolExecutor$Worker.runThreadPoolExecutor.java:587
12java.lang.Thread.runThread.java:841
`

and my method implementation is:

```
   private Emitter.Listener onSocketConnectError = new Emitter.Listener() {
        @Override
        public void call(Object... args) {

            Exception obj = (Exception)args[0];  // Weirdness happens here !!
            Log.i("CONNECT ERR", obj.getLocalizedMessage());

        }
    };
```

and socket initialisation is: 

```
private void bindSocketEvents() {
        mSocket.off(Socket.EVENT_CONNECT_ERROR, onSocketConnectError);
        mSocket.off(Socket.EVENT_CONNECT_TIMEOUT, onSocketConnectError);
        mSocket.off("new message", onSocketNewMessage);

        mSocket.on(Socket.EVENT_CONNECT_ERROR, onSocketConnectError);
        mSocket.on(Socket.EVENT_CONNECT_TIMEOUT, onSocketConnectError);
        mSocket.on("new message", onSocketNewMessage);
        mSocket.connect();

        JSONObject jsonMsg = new JSONObject();
        try {
            jsonMsg.put("id", driver.ID);
        } catch (JSONException je) {
            je.printStackTrace();
        }

        mSocket.emit("add-client", jsonMsg);
    }
```

Can you please advice what is wrong? many thanks

**Comment by nkzawa** [comment]
The first argument of `Socket.EVENT_CONNECT_TIMEOUT event` is long.
I recommend to check type of arguments before using it.

**Comment by alekperos** [comment]
Many thanks for help. solved issue.
