### ISSUE TITLE
Issue with com.github.nkzawa.emitter.Emitter 

### ISSUE THREAD

**Issue by raviteja06** [nkzawa/socket.io-client.java#192]
java.lang.NullPointerException: Attempt to invoke virtual method 'com.github.nkzawa.emitter.Emitter com.github.nkzawa.engineio.client.Transport.once(java.lang.String, com.github.nkzawa.emitter.Emitter$Listener)' on a null object reference : at com.github.nkzawa.engineio.client.Socket$7.call(Socket.java:333)

**Comment by raviteja06** [comment]
Can some one help me to fix this nullpointer.

**Comment by anuragopenxcell** [comment]
I have been facing the same issue with version 0.5.2

**Comment by raviteja06** [comment]
I am only getting this error when i do an emit in listener.

**Comment by nkzawa** [comment]
Duplicate of https://github.com/nkzawa/socket.io-client.java/pull/148.
