### ISSUE TITLE
 java.lang.NoClassDefFoundError: com.squareup.okhttp.OkHttpClient

### ISSUE THREAD

**Issue by therockorchid** [nkzawa/socket.io-client.java#194]
Hello all, I referenced this lib through maven into my android project. I am getting the below issue.
 unable to find class referenced in signature (Lcom/squareup/okhttp/ws/WebSocket;)
unable to find class referenced in signature (Lcom/squareup/okhttp/ws/WebSocket;)
unable to find class referenced in signature (Lcom/squareup/okhttp/ws/WebSocket;)
 Could not find method com.squareup.okhttp.ws.WebSocketCall.cancel, referenced from method com.github.nkzawa.engineio.client.transports.WebSocket.doClose
VFY: unable to resolve virtual method 20499: Lcom/squareup/okhttp/ws/WebSocketCall;

------------ Stack trace-------------
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.client.transports.WebSocket.doOpen(WebSocket.java:45)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.client.Transport$1.run(Transport.java:76)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.thread.EventThread.exec(EventThread.java:50)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.client.Transport.open(Transport.java:71)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.client.Socket.probe(Socket.java:459)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.client.Socket.onOpen(Socket.java:472)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.client.Socket.onHandshake(Socket.java:512)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.client.Socket.onPacket(Socket.java:486)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.client.Socket.access$900(Socket.java:30)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.client.Socket$5.call(Socket.java:300)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.client.Transport.onPacket(Transport.java:124)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.client.transports.Polling.access$700(Polling.java:15)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.client.transports.Polling$2.call(Polling.java:122)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.parser.Parser.decodePayload(Parser.java:251)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.client.transports.Polling._onData(Polling.java:132)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.client.transports.Polling.onData(Polling.java:104)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:115)
08-06 11:25:20.830 I/System.out( 4892):     com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
08-06 11:25:20.830 I/System.out( 4892):     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-06 11:25:20.830 I/System.out( 4892):     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-06 11:25:20.830 I/System.out( 4892):     java.lang.Thread.run(Thread.java:856)

I tried the following:

Downloaded all the dependencies below as mentioned in https://github.com/nkzawa/socket.io-client.java/issues/5
1. socket.io-client-0.1.1(http://search.maven.org/remotecontent?filepath=com/github/nkzawa/socket.io-client/0.1.1/socket.io-client-0.1.1.jar)
2. engine.io-client-0.2.1(http://search.maven.org/remotecontent?filepath=com/github/nkzawa/engine.io-client/0.2.1/engine.io-client-0.2.1.jar)
3. WebSocket-1.3.0(http://search.maven.org/remotecontent?filepath=org/java-websocket/Java-WebSocket/1.3.0/Java-WebSocket-1.3.0.jar)
I have java 6 running on SDK 17.
Still no luck.Should I go with the latest versions of these jars? Please help.

**Comment by nkzawa** [comment]
Recent versions has dependency of OkHttp WebSocket instead of java-websocket.
Please check http://nkzawa.github.io/socket.io-client.java/dependencies.html for the complete dependency list.

**Comment by therockorchid** [comment]
wow, that was quick.. Thanks @nkzawa.

**Comment by therockorchid** [comment]
@nkzawa I referenced below on my project. Still no luck. Is there anything else I need to do? 
<dependency>
			<groupId>com.squareup.okhttp</groupId>
			<artifactId>okhttp</artifactId>
			<version>2.4.0</version>
		</dependency>
		<dependency>
			<groupId>com.squareup.okhttp</groupId>
			<artifactId>okhttp-ws</artifactId>
			<version>2.4.0</version>
		</dependency>

**Comment by therockorchid** [comment]
Forgot to add, I have added the below maven dependency as well.

<dependency>
    		<groupId>com.squareup.okio</groupId>
    		<artifactId>okio</artifactId>
    		<version>1.4.0</version>
		</dependency>

<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20090211</version>
		</dependency>

**Comment by therockorchid** [comment]
@nkzawa    Just to elaborate, I get the below error when I do a maven clean install 


trouble processing:
[INFO] bad class file magic (cafebabe) or version (0033.0000)
[INFO] ...while parsing com/squareup/okhttp/Address.class
[INFO] ...while processing com/squareup/okhttp/Address.class
[INFO] 
[INFO] trouble processing:
[INFO] bad class file magic (cafebabe) or version (0033.0000)
[INFO] ...while parsing com/squareup/okhttp/Authenticator.class
[INFO] ...while processing com/squareup/okhttp/Authenticator.class
[INFO] 
[INFO] trouble processing:
[INFO] bad class file magic (cafebabe) or version (0033.0000)
[INFO] ...while parsing com/squareup/okhttp/Cache$1.class
[INFO] ...while processing com/squareup/okhttp/Cache$1.clas

**Comment by therockorchid** [comment]
Update: Fixed
If someone has the same problem, update your SDK tools to 19 or above.
