### ISSUE TITLE
socket.io LINUX TCP

### ISSUE THREAD

**Issue by c8439** [nkzawa/socket.io-client.java#195]
Client connects to the SOCKET.IO, on-line users, due to the instability of the user network signal, dropped the, and Linux system the user TCP did not release out, the user to connect again socket.io Linux system in adding a TCP.
![t03v3t m oens a fr5hppj](https://cloud.githubusercontent.com/assets/13691096/9160473/baf13cb6-3f6c-11e5-9d70-a686eb8b3fce.jpg)

**Comment by c8439** [comment]
Online users only hundreds of TCP, there were more than 5000, but also continue to add, established
![7 syucl3l 32 cuupa6f3u6](https://cloud.githubusercontent.com/assets/13691096/9160486/cdad4688-3f6c-11e5-8fa2-659a556ec1be.jpg)

**Comment by nkzawa** [comment]
I believe this is the problem of engine.io server rather than the client, and we are addressing it now.

https://github.com/socketio/engine.io/pull/336

**Comment by c8439** [comment]
Socket.io 0.9 version will appear this kind of situation?

**Comment by nkzawa** [comment]
I'm not sure about 0.9.x.

**Comment by nkzawa** [comment]
Closed since this is the problem of server.
