### ISSUE TITLE
Can this be used with any implementation of java?

### ISSUE THREAD

**Issue by dshep4** [nkzawa/socket.io-client.java#199]
I'm using JDK 8 and need to connect to socket io... any suggestions?

**Comment by nkzawa** [comment]
JDK 8 is supported. Do you have any problem with it? What's your problem actually?

**Comment by dshep4** [comment]
No problems.. On another note while I have you here, how reliable is the connection? If it goes down for whatever reason, are there scenarios where it wont know to reconnect due to some event not firing? Do you recommend use in a production environment?
