### ISSUE TITLE
How can I connect to a server with cookie?

### ISSUE THREAD

**Issue by bitjjj** [nkzawa/socket.io-client.java#32]
Because socket.io server will use client cookie to check whether connection is a browser. I want to use cookie to pass through this check.
Thanks a lot.

**Comment by akshaylive** [comment]
Need cookie store! :(

**Comment by hayksaakian** [comment]
if you use this, you will probably be sad, as I was when I found out that the JavaScript socket.io client will never support sending headers. 

see:

https://github.com/Automattic/socket.io-client/issues/648#issuecomment-42154344

In my case, i need to rewrite my API to handle authentication in a separate step -- after connecting.

**Comment by eschwitters** [comment]
@nkzawa Your example seems to work except that the Transport headers are actually a Map<String>, List<String>> in the PollingXHR class.

Not sure why they need to be a Map of Lists not just a Map of Strings?
