### ISSUE TITLE
Is possible to get socket identifier?

### ISSUE THREAD

**Issue by Marabita** [nkzawa/socket.io-client.java#67]
Hi, Im trying to retrieve socket id after connection, is it possible?

    /**
     * Listen for connection callback on socket
     */
    private Emitter.Listener mOnConnectCallback = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            Log.e(TAG, "Socket Connected");
            <!!!>
        }
    };

**Comment by nkzawa** [comment]
This will be available on the next release!

**Comment by nkzawa** [comment]
You can `socket.id()` now.

**Comment by Marabita** [comment]
Great! Tks @nkzawa !

**Comment by matt2405warner** [comment]
I must be doing something wrong because `socket.id()` returns null....
