### ISSUE TITLE
Working with socket.io 1.0.6 ?

### ISSUE THREAD

**Issue by letroll** [nkzawa/socket.io-client.java#71]
Hello,

currently I'm using an [webapp](https://github.com/DaftMonk/generator-angular-fullstack#usage) which use socket.io 1.0.6 , but when I want to connect, no connect event are fired and the console of my webapp return :

```json

GET /socket.io/?EIO=3&transport=polling 200 2ms
GET /socket.io/?EIO=3&transport=polling 200 3ms
GET /socket.io/?EIO=3&transport=polling 200 56ms
GET /socket.io/?EIO=3&transport=polling 200 2ms
GET /socket.io/?EIO=3&transport=polling 200 4ms
GET /socket.io/?EIO=3&transport=polling 200 2ms
GET /socket.io/?EIO=3&transport=polling 200 2ms
GET /socket.io/?EIO=3&transport=polling 200 35ms
GET /socket.io/?EIO=3&transport=polling 200 35ms
GET /socket.io/?EIO=3&transport=polling 200 4ms

````

Can you help me to solve that?

**Comment by nkzawa** [comment]
@sarvajeet294 please create another issue if you still have the problem.

**Comment by deepakdahal** [comment]
Hi @nkzawa, I am using 0.5.2(latest) version of your socketio client and still getting the xhr poll error. My server version is 1.3.6(http://socket.io/)
error: com.github.nkzawa.engineio.client.EngineIOException: xhr poll error
Do you see a problem with these versions?

**Comment by nkzawa** [comment]
You library versions are OK. I think it's a different problem.
