### ISSUE TITLE
Java-WebSocketClient loop endless when disconnect

### ISSUE THREAD

**Issue by YoungSeung-Seo** [nkzawa/socket.io-client.java#72]
Hi! I'm using your java socket.io library thankfully. 

But I've faced with some problem in Java-WebSocketClient v1.3.0

Please check link below

https://github.com/TooTallNate/Java-WebSocket/issues/171

It looks like resolved in latest Java-WebSocketClient version.

Do you have a plan to update the Java-WebSocketClient library to latest version? 

thanks.

**Comment by shuoli84** [comment]
@nkzawa  close this?

**Comment by BrushfireDigitalServices** [comment]
FYI, the endless loop issue should now be fixed on the master branch at TooTallNate/Java-Wobsocket. Updating the version number and jar are on the to-do list. If problems persist for projects depending on Java-Websocket, please tell us as soon as possible.
