### ISSUE TITLE
Unable to connect to Server

### ISSUE THREAD

**Issue by madhumita1** [nkzawa/socket.io-client.java#75]
I am unable to connect to server using this library neither I am getting any error message.
I am using following jars:
1. socket.io-client-0.2.0.jar
2. engine.io-client-0.3.0.jar
3. Java-WebSocket-1.3.0.jar
Sometimes I am getting "com.github.nkzawa.socketio.client.SocketIOException: timeout".

How can I resolve this?
How can I check the socket status, whether it is connected to server or not?

**Comment by nkzawa** [comment]
Can you post your code and logs? I'm sorry, should check your issue first but the issue #81 might be helpful for you too.

**Comment by nkzawa** [comment]
Closed due to inactivity. Feel free to reopen it if you still have the problem.
