### ISSUE TITLE
Non of the callback methods getting called with a timeout error

### ISSUE THREAD

**Issue by madhumita1** [nkzawa/socket.io-client.java#77]
I am getting "com.github.nkzawa.socketio.client.SocketIOException: timeout" error while trying to connect to a "HTTPS" server.
And non of the callback methods is getting called except CONNECT_ERROR.
What could be the reason?

**Comment by nkzawa** [comment]
You have to implement jsonp transport by yourself if you definitely need it.
But I wonder why it's required for you? Usually, jsonp is only for browser.
