### ISSUE TITLE
Memory Leak: keeping a fragment reference when opening/closing it multiple times

### ISSUE THREAD

**Issue by abdelhady** [nkzawa/socket.io-client.java#78]
I have a fragement that shows an image pager, & I'm opening a socket in it, to be notified if any photo has been added to the album, the code is like this:

in `onCreateView`:
````java
String query = "?token=" + URLEncoder.encode(Utils.getAccessToken(getActivity()), "UTF-8");
socket = IO.socket(URLs.ServerUrl + liveAlbumNamespace + query);
socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
    @Override
    public void call(Object... args) {
        JSONObject params = new JSONObject();
        params.put("Album", String.valueOf(albumId));
        socket.emit("join live album room", params);
    }
 }).on("new photo", new Emitter.Listener() {
    @Override
    public void call(Object... args) {
        JSONObject obj = (JSONObject) args[0];
        imagesDownloader.startDownload(); // imagesDownloader is a member variable in the fragment
    }
});
````

in `onResume`:
````java
socket.connect();
````

in `onPause`:
````java
socket.disconnect();
````

Then I found that the socket always keeps a reference to the current fragment even if I used `socket.close()` in `onDestroy`
the only thing that enhanced this behavior is by using the option `options.forceNew = true` when creating the socket, but the problem is that `forceNew` will delete old fragment reference only when creating a new instance of the socket, but until then it will keep a reference to the destroyed fragment no matter what I did,

**So**, how I make sure that when I close the socket it won't keep a reference to the current fragment/activity?

**Comment by nkzawa** [comment]
What if you remove all listeners when disconnecting?

`socket.off();`

**Comment by abdelhady** [comment]
I was looking for a method to remove all listeners but I didn't find it, 
now, I've tried `socket.off()` & it is working perfectly without even the need to use the option `forceNew`,
Thanks a lot nkzawa :+1: 

note:
I thought that `socket.close()` will remove all listeners, so I tried it before but it didn't help me,
So, I think it would be better if you added this scenario to the library's Readme page, because having a memory leak like that could get very nasty so quickly.
