### ISSUE TITLE
I use socket.emit in the socket.on()'s context in the serverside using nodejs, but in this situation, mobile can not receive the message from serverside?

### ISSUE THREAD

**Issue by monokeroslun** [nkzawa/socket.io-client.java#80]
serverside code : socket.on('event1',function(){
socket.emit('android',"kkk")
})

when I trigger the event1 from mobileside, the serverside triggers the android event,  but the mobileside cannot receive the message kkk,but if the client is browser, it's ok. why?

**Comment by nkzawa** [comment]
Can you post your code of android here? Especially how you listen `android` event.

**Comment by monokeroslun** [comment]
Thanks for your reply, I get the point. It's my fault.      ~^ _ ^~
