### ISSUE TITLE
Unable to create a connection

### ISSUE THREAD

**Issue by Ahmad19860** [nkzawa/socket.io-client.java#81]
Hi, 
I am trying to connect to my socket server using socket-io library. But I am getting SocketIOException. Please suggest the reason.
I am using the below jar files downloaded from "http://mvnrepository.com/artifact/com.github.nkzawa/socket.io-client"
engine.io-client-0.3.1.jar
socket.io-client-0.3.0.jar
Java-WebSocket-1.3.0.jar

On the other hand, everything is working fine in phonegap app for ios using nodeJs. But I am unable to connect in android native app. I also tried with this library "https://github.com/Gottox/socket.io-java-client". but no success. Please suggest the way so that I can implement this.

**Comment by nkzawa** [comment]
Needs more information. Any logs? Can you post your code?

**Comment by Ahmad19860** [comment]
Hi,
Thanks for your quick reply. I am sharing the code which I used to make a connection.

Socket socket;
	private void test() {
		try {
			socket = IO.socket("http://54.86.103.211:8080");
			socket.connect(); // initiate connection to socket server			
		} catch (URISyntaxException e) {
			e.printStackTrace();
		}
		
		socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {

			@Override
			public void call(Object... args) {
				Log.d("socketio", "socket connected");
				socket.emit("chat message",
						"even connect: message sent from android to socketio server");
				// socket.disconnect(); // why is there a disconnect here?
			}
		}).on(Socket.EVENT_MESSAGE, new Emitter.Listener() {

			@Override
			public void call(Object... arg0) {
				// TODO Auto-generated method stub
				Log.d("socketio", "socket event message" + arg0);
				socket.emit("chat message",
						"android to server from event message");
			}
		});

		// 2nd segment test without connecting to 1 long method
		socket.on(Socket.EVENT_CONNECT_ERROR, new Emitter.Listener() {
			@Override
			public void call(Object... arg0) {
				// TODO Auto-generated method stub
				Log.d("socketio", "socket event connect error");
				socket.emit("chat message",
						"android to server: socket event connect error");
			}
		});

		socket.on(Socket.EVENT_MESSAGE, new Emitter.Listener() {

			@Override
			public void call(Object... arg0) {
				// TODO Auto-generated method stub
				Log.d("socketio", "socket event message" + arg0);
				socket.emit("chat message",
						"android to server from event message");
			}
		});		
	}


 After running this code, Socket.EVENT_CONNECT_ERROR is called with object having value "[com.github.nkzawa.socketio.client.SocketIOException: timeout]". There is no log message in logcat window. Please suggest where I am doing wrong. Please tell me if any more information you need. from my side

**Comment by nkzawa** [comment]
did you add `android.permission.INTERNET`?

**Comment by Ahmad19860** [comment]
yes...

**Comment by Ahmad19860** [comment]
I am struggling last three days, but no success to find the reason...

**Comment by nkzawa** [comment]
Can you post server code too?

**Comment by nkzawa** [comment]
And logs with debug enabled (`DEBUG=* node server.js`) ?

**Comment by Ahmad19860** [comment]
no i don't have the access to server code. Is there any possibility of issue in server code as everything is working in phonegap app?

**Comment by nkzawa** [comment]
For example, the version of socket.io is older than supported, or the server has special settings, etc.

btw, I can't access to http://54.86.103.211:8080/socket.io with browser. Is the server still running?
If it's running, you can usually see the page like http://chat.socket.io/socket.io.

**Comment by Ahmad19860** [comment]
Ok, I will discuss this and update you soon. Hopefully it will help me.

And, thanks a lot once again for your response.

**Comment by Ahmad19860** [comment]
@nkzawa I talked to the person who is responsible for server side development. He is saying that GET request will not work,that is why  http://54.86.103.211:8080/socket.io is not working. Server is running and used version is v0.10.29. Is this information is helpful to find a fix for my issue.

**Comment by nkzawa** [comment]
v0.10.29 sounds the version of node.js. There is no v0.10.29 on socket.io.
And I wonder how phonegap is working without GET request.

**Comment by Ahmad19860** [comment]
oh, can you suggest me how to check socket.io version. i will try to check it myself.

**Comment by nkzawa** [comment]
check package.json if you can see the source code.

https://docs.npmjs.com/files/package.json

**Comment by Ahmad19860** [comment]
@nkzawa Millions thanks for your valuable time. Actual issue was not able to access  http://54.86.103.211:8080. So as per your hint I talked to network team, they opened the port and all is working fine now. :+1:

**Comment by nkzawa** [comment]
:+1:

**Comment by phamhuusam** [comment]
@nkzawa @Ahmad19860 Hello I have problem, Can you help me?
I follow code at page: http://socket.io/blog/native-socket-io-and-android/
and download, run successfully project https://github.com/nkzawa/socket.io-android-chat.
And I want to connect socket io with my node server

Code at: server 

var socketIO = require('socket.io'),
	http = require('http'),
	port = process.env.PORT || 8080,
	ip = process.env.IP || '192.168.0.105', //My IP address. I try to "127.0.0.1" but it the same => don't run
	server = http.createServer().listen(port, ip, function() {
		console.log("IP = " , ip);
		console.log("start socket successfully");
});

io = socketIO.listen(server);
//io.set('match origin protocol', true);
io.set('origins', '*:*');

var run = function(socket){
	
	socket.on("message", function(value) {
		console.log(value);
	});

	socket.on("user-join", function(value) {
		console.log(value + "user-join");
		socket.broadcast.emit("new-users", value);

	});
}

io.sockets.on('connection', run);

Code at Android:

package com.example.phamhuu.chatnodejs;
import android.os.Bundle;
import android.support.v7.app.ActionBarActivity;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;

import com.github.nkzawa.socketio.client.IO;
import com.github.nkzawa.socketio.client.Socket;

import java.net.URISyntaxException;


public class MainActivity extends ActionBarActivity {
    private Socket mSocket;
    {
        try {
            //mSocket = IO.socket("192.168.3.1:8080");
            IO.Options options = new IO.Options();
            options.port = 8080;
            mSocket = IO.socket("http://192.168.0.105:8080");
            //mSocket = IO.socket("http://chat.socket.io");
        } catch (URISyntaxException e) {
            Log.e("abc", "index=" + e);
        }
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mSocket.connect();
        Log.e("result socket connect", String.valueOf(mSocket.connected()));
        mSocket.emit("message", "Send message to server.");
    }


    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }
}

I try it but socket can't connect to server at address: 192.168.0.105 port: 8080
Can you help me?
Thanks very much.

**Comment by nkzawa** [comment]
@phamhuusam Hmm, I have no idea ... Any errors or logs? Can you connect to https://github.com/Automattic/socket.io/tree/master/examples/chat ?

**Comment by vooratarun** [comment]
I am trying to connect on android.
 But it is getting "failed to connect" onError


public class ChatApplication extends Application {

    private Socket mSocket;
    {
        try {
            IO.Options options = new IO.Options();
            options.forceNew = true;

            options.port = 3000;
            mSocket = IO.socket("http://192.168.0.101",options);
        } catch (URISyntaxException e) {
            throw new RuntimeException(e);
        }
    }

    public Socket getSocket() {
        return mSocket;
    }
}

**Comment by leolima** [comment]
same error here

**Comment by ahmadtahir1919** [comment]
Socket disconnect if Android mobile is in PowerSaving Mode
If mobile is in powerSaving mode Socket Always trigle on reconnecting event
1:-Code is in service
2:-If turn Off the powerSaving mode Socket working fine
Any Solution?

**Comment by IshanFx** [comment]
try to add  options.transports = new String[]{WebSocket.NAME};

**Comment by thebishal108** [comment]
how to print the mSocket after it has been generated with mOptions
