### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1, fault

### ISSUE THREAD

**Issue by holoduke** [nkzawa/socket.io-client.java#82]
I am receiving the message in Android 5.x only always in the following example

            socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
                public void call(Object... args) {
                    socket.emit("joinroom","12345", new Ack() {
                        public void call(Object... arg0) {
                     
                            ///this is where the fatal exception is thrown
                            getListView().setAdapter(adapter);
                        }
                }
            }
}

now i have tried to wrap code inside the "call" callback from Ack like:

getView().post(new Runnable(){
      public void run() {
              ....
      } 
}

but also with a Handler or a new Thread.
Nothing helps. keep getting the  Fatal signal 11 (SIGSEGV), code 1, fault.

Any idea what this might be?

**Comment by nkzawa** [comment]
Umm, I have no idea but I think this issue is not due to socket.io-client.
The following stackoverflow might be helpful: http://stackoverflow.com/questions/17840521/android-fatal-signal-11-sigsegv-at-0x636f7d89-code-1-how-can-it-be-tracked

**Comment by shuoli84** [comment]
Close this? As not related with this project. @nkzawa @holoduke

**Comment by vincepunkrock** [comment]
@holoduke I know this was a long time ago, but I just have the same problem. Did you find an answer to your question somewhere? Or did you find the solution to your problem?
