### ISSUE TITLE
Many Socket references when my activity onResume.

### ISSUE THREAD

**Issue by njpalmin** [nkzawa/socket.io-client.java#83]
How can I destroy socket reference when my activity finish, and if I want to reuse it, how should I do. 

Looks like I use mSocket = IO.Socket(), and my activity exits, I set it to null, and then relaunch the activity, it will be created by mSocket = IO.Socket, but I got the null error when I use mSocket.emit.

**Comment by nkzawa** [comment]
I recommend to remove all listeners of `mSocket` when `onDestroy` like `mSocket.off("myevent")`.

For the `null` error, it's your responsible to manage since `IO.socket()` always return a socket instance.
