### ISSUE TITLE
The program not closed after socket.close()

### ISSUE THREAD

**Issue by gvan** [nkzawa/socket.io-client.java#85]
Hi.
I wrote the test code snippet:

    public static void main(String [] args){
        IO.Options options = new IO.Options();
        options.forceNew = true;
        options.reconnection = false;

        Socket socket = null;
        try {
            socket = IO.socket("http://localhost:9092", options);
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }

        socket.on("hello", objects -> System.out.println(objects[0]));

        socket.connect();
        //Wait for q to close
        BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(System.in));
        String s;
        while(true){
            try {
                s = bufferedReader.readLine();
                if(s.equals("q"))
                    break;
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        socket.off();
        socket.close();
    }
All works fine, client gets the messages from server and after entering 'q' the programm stops.
But I have two problems:

1) When the server not runned. The socket not connected (socket.connected()). After pressing 'q' socket call close() but programm still working. I look at debugger and find there EventThread in runnable state. How I can stop this thread?

2) When the server is run and the section 'Wait for q to close' is comment. Then close() method colled immediately after connect(). In this situation the programm still working too.

**Comment by Dayyoung** [comment]
i solved by this : 

		// TODO Auto-generated method stub
		try {
			socket = IO.socket(url);
			System.out.println("Connecting~~~ ");
			socket.off();
			System.out.println("INIT~~~ ");
		} catch (URISyntaxException e) {
			e.printStackTrace();
		}
  
i think it is IO problem. init IO Class.

**Comment by nkzawa** [comment]
Umm, this issue may be a bug of the library. I will try to reproduce it.

**Comment by nkzawa** [comment]
This would be fixed on the next release.

**Comment by nkzawa** [comment]
Fixed on v0.4.1. Thanks for your report!
