### ISSUE TITLE
socket.io-client.java couldn't pass ack to socket.io server (v1.3.2)

### ISSUE THREAD

**Issue by lustroz** [nkzawa/socket.io-client.java#89]
I had sent to socket.io server (v1.2.0) ack argument successfully as follows:

<pre>
JSONObject json = new JSONObject();
json.put("key", "value");
socket.emit("message", json, new Ack() {
    @Override
    public void call(Object... args) {
        ...
    }
});
</pre>

But, the above routine isn't not working properly anymore since server socket.io version is changed to v1.3.2.

**Comment by nkzawa** [comment]
I am working to make the lib compatible with v1.3.2.

**Comment by lustroz** [comment]
Thank you so much. :)

나의 iPhone에서 보냄

2015. 1. 26. 오후 12:17 Naoyuki Kanezawa <notifications@github.com> 작성:

I am working to make the lib compatible with v1.3.2.

—
Reply to this email directly or view it on GitHub
<https://github.com/nkzawa/socket.io-client.java/issues/89#issuecomment-71410202>
.

**Comment by nkzawa** [comment]
Umm I couldn't reproduce this. Anyway I'm going to release a new version.

**Comment by nkzawa** [comment]
I released a new version v0.4.0. Could you try it?

**Comment by lustroz** [comment]
Thank you for your kind but I can't try it now at home. I would try it in
hours and will send the result to you.

나의 iPhone에서 보냄

2015. 1. 29. 오전 1:14 Naoyuki Kanezawa <notifications@github.com> 작성:

I released a new version v0.4.0. Could you try it?

—
Reply to this email directly or view it on GitHub
<https://github.com/nkzawa/socket.io-client.java/issues/89#issuecomment-71862481>
.

**Comment by lustroz** [comment]
It works very well. Thanks!!

**Comment by nkzawa** [comment]
:smile:
