### ISSUE TITLE
Not automatically reconnecting

### ISSUE THREAD

**Issue by supreddy** [nkzawa/socket.io-client.java#90]
Hi,

I am testing the latest socket.io-client.java with socket.io 1.2.1. I use 
IO.Options opts = new IO.Options();
opts.forceNew = true;

as connection parameter. I am able to connect to the server and my test chat app runs brilliantly till it sometimes disconnects from client side (Android). After which I need to restart my activity to re-establish the connection to the socket.io server. Why is the reconnection not happening automatically?

Also, when I try IO.socket("http://ipaddress:3000", opts); again without restarting my Android activity, it keeps connecting and disconnecting continuously. Is this a known behavior or am I doing something wrong?

**Comment by Neshfi** [comment]
Try adding `opts.reconnection = true;` to your options.

**Comment by supreddy** [comment]
I tried with the opts.reconnection = true; still facing the same issue. How does the reconnection option work?

**Comment by Neshfi** [comment]
Since this library is basically a port of the original Socket.IO you might be able to use the information that you can find here: http://socket.io/docs/client-api/#manager%28url:string,-opts:object%29

As on the "till it sometimes disconnects from client side" part. Could it be that your socket gets garbage collected?

**Comment by nkzawa** [comment]
Can you post your code here?

**Comment by oliverhausler** [comment]
I am seeing an issue which may or may not be related. I am also using the library on Android, and the server was down while or after I connected. About 5 minutes later, Android crashed with the following stack trace (sorry, only as screenshot).

[I am totally new to socket.io, so I may have made a mistake. Here's my code:

                IO.Options options = new IO.Options();
                options.forceNew = true;
                options.reconnection = true;

                try {
                    socket = IO.socket("http://192.168.0.2:8080", options);
                } catch (URISyntaxException e) {
                    throw new RuntimeException("Socket connection failed.", e);
                }
                socket.connect().emit("token", base64encodedstring);

]

![screenshot_2015-03-01-12-55-57](https://cloud.githubusercontent.com/assets/8090341/6432805/a3f76252-c013-11e4-81e4-2a1d363dc7fa.png)

**Comment by shuoli84** [comment]
Any idea on when this will get fixed?

**Comment by shuoli84** [comment]
This already fixed by d6e22703, close it? @nkzawa

**Comment by nkzawa** [comment]
Closed but feel free to reopen if you still have the problem. Thx, @shuoli84 :smiley:

**Comment by pankajtalaviya97** [comment]
Use 0.8.3 version of io.socket remove new version 1.0.0

compile('io.socket:socket.io-client:0.8.3') {
    exclude group: 'org.json', module: 'json'
}

**Comment by october7sveryown** [comment]
> Hi,
> 
> I am testing the latest socket.io-client.java with socket.io 1.2.1. I use
> IO.Options opts = new IO.Options();
> opts.forceNew = true;
> 
> as connection parameter. I am able to connect to the server and my test chat app runs brilliantly till it sometimes disconnects from client side (Android). After which I need to restart my activity to re-establish the connection to the socket.io server. Why is the reconnection not happening automatically?
> 
> Also, when I try IO.socket("http://ipaddress:3000", opts); again without restarting my Android activity, it keeps connecting and disconnecting continuously. Is this a known behavior or am I doing something wrong?

Facing the same issue on network change. What solved your issue? Please share the same.
