### ISSUE TITLE
Emitter.Listener call() async or synchronous? 

### ISSUE THREAD

**Issue by paxos1977** [nkzawa/socket.io-client.java#91]
This is a silly question not an issue... 

Was wondering if Emitter.Listener call()'s will be invoke one at a time (synchronously) or if there may be more than one in-flight at a time. Obviously, in the javascript socket.io there should only be one in-flight at a time, but curious about this since it's java.

**Comment by nkzawa** [comment]
` Emitter.Listener#call()` will be invoked one at a time since all internal processes of the lib is single thread like Node.JS.

**Comment by paxos1977** [comment]
@nkzawa thanks, I assumed it would be single threaded like the node.js implementation but I wanted to know for sure. You saved me a lot of reading & I appreciate it.
