### ISSUE TITLE
Version change

### ISSUE THREAD

**Issue by njpalmin** [nkzawa/socket.io-client.java#94]
I noticed that you committed some changes, but the version is still 0.3.0, so no change for this in build.gradle?

compile 'com.github.nkzawa:socket.io-client:0.3.0'

Thanks!

**Comment by nkzawa** [comment]
I was thinking to fix some issues, but will release 0.4.0 asap and fix issues in the subsequent minor releases.

**Comment by nkzawa** [comment]
v0.4.0 is out.
