### ISSUE TITLE
ClassCastException when trying to (string)args received

### ISSUE THREAD

**Issue by dimitrilahaye** [nkzawa/socket.io-client.java#95]
Hello ! I'm working with a nodeJS server. It sends me datas, but at line 319 of Socket.java, it creates me a classcastException -->
Here the stack :
Exception in thread "EventThread" java.lang.ClassCastException: [B cannot be cast to java.lang.String
	at com.github.nkzawa.socketio.client.Socket.onevent(Socket.java:319)
	at com.github.nkzawa.socketio.client.Socket.onpacket(Socket.java:288)
	at com.github.nkzawa.socketio.client.Socket.access$1(Socket.java:275)
	at com.github.nkzawa.socketio.client.Socket$2$2.call(Socket.java:105)
	at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
	at com.github.nkzawa.socketio.client.Manager.ondecoded(Manager.java:381)
	at com.github.nkzawa.socketio.client.Manager.access$13(Manager.java:380)
	at com.github.nkzawa.socketio.client.Manager$3.call(Manager.java:353)
	at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
	at com.github.nkzawa.socketio.parser.Parser$Decoder.add(Parser.java:167)
	at com.github.nkzawa.socketio.client.Manager.ondata(Manager.java:377)
	at com.github.nkzawa.socketio.client.Manager.access$12(Manager.java:375)
	at com.github.nkzawa.socketio.client.Manager$2.call(Manager.java:346)
	at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
	at com.github.nkzawa.engineio.client.Socket.onPacket(Socket.java:485)
	at com.github.nkzawa.engineio.client.Socket.access$900(Socket.java:29)
	at com.github.nkzawa.engineio.client.Socket$5.call(Socket.java:288)
	at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
	at com.github.nkzawa.engineio.client.Transport.onPacket(Transport.java:121)
	at com.github.nkzawa.engineio.client.Transport.onData(Transport.java:117)
	at com.github.nkzawa.engineio.client.transports.WebSocket.access$200(WebSocket.java:19)
	at com.github.nkzawa.engineio.client.transports.WebSocket$1$4.run(WebSocket.java:83)
	at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

And, see the image following, to see the content of my args at this moment.

![img](https://cloud.githubusercontent.com/assets/7722597/5940482/703ca1a0-a70b-11e4-9377-d2d65d7f8a61.png)

Have you any idea to debug this ?

**Comment by nkzawa** [comment]
can you post your code? server and client

**Comment by dimitrilahaye** [comment]
Thanks for the speed ;)
Client side :

//My test :

@Test
public void eventAskBinaryMessageWithNoAck() throws URISyntaxException,
    InterruptedException {
        this.initSockets(1);
        final BlockingQueue < Object > values = new LinkedBlockingQueue < Object > ();
        mySocket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {

            @
            Override
            public void call(Object...args) {
                System.out.println("Connect at EventAskBinaryMessageWithNoAck");
                mySocket.send("EventAskBinaryMessageWithNoAck", dataDic);
            }
        }).on("message", new Emitter.Listener() {

            @
            Override
            public void call(Object...args) {
                JSONObject obj = (JSONObject) args[0];
                System.out.println("args on 'message' event : " + obj.toString());
            }

        }).on(Socket.EVENT_ERROR, new Emitter.Listener() {

            @
            Override
            public void call(Object...args) {
                mySocket.disconnect();
            }

        }).on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {

            @
            Override
            public void call(Object...args) {
                System.out.println("Disconnect from EventAskBinaryMessageWithNoAck");
            }

        });
        mySocket.connect();
        //don't worry with these asserts...
        assertEquals(values.take().getClass(), Ack.class);
        assertThat((String) values.take(), is("Binary Ack"));
    }

//My initialisation of sockets :

private String secured(boolean _b) {
    String b = (_b) ? "https" : "http";
    return b;
}

private void createSocket(boolean sec, String host, int port, String nsp,
    String query, long timeout) throws URISyntaxException {
    String s = secured(sec);
    String q = (query == "") ? null : query;
    URI uri = new URI(s, null, host, port, null, q, null);
    Options opt = new Options();
    String[] ws = {
        "websocket"
    };
    opt.transports = ws;
    opt.rememberUpgrade = true;
    Manager io = new Manager(uri, opt);
    io.timeout(timeout);
    mySocket = new Socket(io, nsp);
}

public void initSockets(int i) throws URISyntaxException {
    switch (i) {
        case 1:
            this.createSocket(false, "localhost", 8080, "/", "", 1000);
            break;
        case 2:
            this.createSocket(false, "localhost", 8080, "/public", "", 1000);
            break;
        case 3:
            this.createSocket(false, "localhost", 8080, "/private",
                "login=fail", 1000);
            break;
        case 4:
            this.createSocket(false, "localhost", 8080, "/private",
                "login=hello", 1000);
            break;
        default:
            break;
    }
}




Server side :

//Server.js
var Socket = require('./Socket')
var Server = module.exports;

Server.connect = function(socket) {
    console.log("Client Connected :", socket.client.conn.remoteAddress, "ON", socket.nsp.name);

    socket.on('disconnect', Socket.disconnect);

    socket.on('message', Socket.message);

    socket.on('EventAskBinaryMessageWithNoAck', Socket.binaryMessageWithNoAck);

}


//Socket.js
var Socket = module.exports;

Socket.message = function(message, func) {
    console.log(message);
    if (func) {
        if (message === 'MessageWithAck')
            func('Simple Ack');
        else if (message === 'MessageWithBinaryAck')
            func(new Buffer("Binary Ack", 'binary'));
    }
}

Socket.binaryMessageWithNoAck = function(data, func) {
    var socket = this.server.sockets.connected[this.client.id];
    socket.emit(new Buffer("Binary message", 'binary'));
}

Socket.disconnect = function(func) {
    console.log("Client Disconnected :", this.client.conn.remoteAddress);

    for (var id in this.server.of('/').connected) {
        console.log("Send disconnect from :", this.id, 'to :', id);

        this.server.of('/').connected[id].client.server.emit('disconnect', {
            'from': this.id
        });
    };
}

//App.js :

var app = require('express')();
var server = require('http').Server(app)
var io = require('socket.io')(server);
var Server = require('./Server');
server.listen(8080);

io.of('/private').use(Server.auth).on('connection', Server.connect);
io.of('/public').on('connection', Server.connect);
io.on('connection', Server.connect);

**Comment by nkzawa** [comment]
@dimitrilahaye thx but could you make it simple so that I can understand where is the problem?

**Comment by dimitrilahaye** [comment]
Sorry, ok :

Server side :

//Server.js
var Socket = require('./Socket')
var Server = module.exports;

Server.connect = function(socket) {
    socket.on('message', Socket.message);
    socket.on('EventAskBinaryMessageWithNoAck', Socket.binaryMessageWithNoAck);
}
//Socket.js
var Socket = module.exports;
Socket.message = function(message, func) {
    console.log(message);
    func(new Buffer("Binary Ack", 'binary'));
}
Socket.binaryMessageWithNoAck = function(data, func) {
    var socket = this.server.sockets.connected[this.client.id];
    socket.emit(new Buffer("Binary message", 'binary'));
}
//App.js :
var app = require('express')();
var server = require('http').Server(app)
var io = require('socket.io')(server);
var Server = require('./Server');
server.listen(8080);
io.of('/private').use(Server.auth).on('connection', Server.connect);
io.of('/public').on('connection', Server.connect);
io.on('connection', Server.connect);

Client side :

//My test :

//a ditionnary to send :
Hashtable < String, String > dataDic = new Hashtable < String, String > ();
dataDic.put("var01", "value01");
dataDic.put("var00", "value00");

@
Test
public void eventAskBinaryMessageWithNoAck() throws URISyntaxException,
    InterruptedException {
        Socket mySocket = IO.socket("http://localhost:8080");

        final BlockingQueue < Object > values = new LinkedBlockingQueue < Object > ();
        mySocket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {

            @
            Override
            public void call(Object...args) {
                mySocket.send("EventAskBinaryMessageWithNoAck", dataDic);
            }
        }).on("message", new Emitter.Listener() {

            @
            Override
            public void call(Object...args) {
                JSONObject obj = (JSONObject) args[0];
            }

        }).on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {

            @
            Override
            public void call(Object...args) {}

        });
        mySocket.connect();
        //don't worry with these asserts...
        assertEquals(values.take().getClass(), Ack.class);
        assertThat((String) values.take(), is("Binary Ack"));
    }

**Comment by nkzawa** [comment]
`socket.emit(new Buffer("Binary message", 'binary'));` looks weird. you can't do this.

**Comment by dimitrilahaye** [comment]
It is what we did with the Objective-C Socket.io client :
https://github.com/louis49/SocketIO-Objc/
Why is it weird in your opinion ?

**Comment by nkzawa** [comment]
because the first argument of `emit` has to be a string, not a Buffer instance.

**Comment by nkzawa** [comment]
`mySocket.send("EventAskBinaryMessageWithNoAck", dataDic);` is also wrong, because you can't send `Hashtable`. This has to be a `JSONObject`.

**Comment by dimitrilahaye** [comment]
For your point on server side, even if i put 
socket.emit("message", new Buffer("Binary message", 'binary'));
It doesn't pass.

But I will try with JSON on client side. Thanks !

**Comment by dimitrilahaye** [comment]
You were absolutly right and I was wrong :
socket.emit("message", new Buffer("Binary message", 'binary')); --> works and obviously, JSON Object too.
Thanks again !

**Comment by nkzawa** [comment]
:smile:
