### ISSUE TITLE
Namespaces aren't managed on reception

### ISSUE THREAD

**Issue by dimitrilahaye** [nkzawa/socket.io-client.java#97]
Hello again !
When I use namespace and I'm waiting for a message with datas (binaries or not), the datas never arrive.
Exactly, I send fake datas to the server, because I want the server send me event with datas. If I use namespace, I receive datas (here, it will be binary datas), but I loose it somewhere and I don't know where and why.
Here my example, hoping it is clear enough :

```java
// Client side

public void EventAskBinaryEventWithNoAck() throws URISyntaxException,
    InterruptedException, JSONException {
        //here, i'm creating my socket. Perhaps the matter is here.
        //After this piece of code, I will show you how I create the socket.
        mySocket = this.createSocket("http", "localhost", 8080, "/public", "", 1000);
        final BlockingQueue < Object > values = new LinkedBlockingQueue < Object > ();
        mySocket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {

            @
            Override
            public void call(Object...args) {
                mySocket.emit("EventAskBinaryEventWithNoAck", dataDic); //dataDic is JSONObject
            }
        }).on("BinaryEventWithNoAck", new Emitter.Listener() {

            @
            Override
            public void call(Object...args) {
                // I know I never pass in this...
                Object out = handlerMessage(args[0]);
                values.offer(out);
            }

        });
        mySocket.connect();
    }

//How I create socket

private void createSocket(String sec, String host, int port, String nsp,
    String query, long timeout) throws URISyntaxException {
    String q = (query == "") ? null : query;
    URI uri = new URI(sec, null, host, port, nsp, q, null);
    Options opt = new Options();
    String[] ws = {
        "websocket"
    };
    opt.transports = ws;
    opt.rememberUpgrade = true;
    opt.query = q;
    opt.host = host;
    opt.port = port;
    opt.timeout = timeout;
    opt.path = null;
    Manager io = new Manager(uri, opt);
    io.timeout(timeout);
    mySocket = new Socket(io, nsp);
}
```

```javascript
// Server side

// Server.js
var Socket = require('./Socket')
var Server = module.exports;
//...
Server.connect = function(socket) {
    socket.on('EventAskBinaryEventWithNoAck', Socket.eventAskBinaryEventWithNoAck);
}

//Socket.js
var Socket = module.exports;
//...
Socket.eventAskBinaryEventWithNoAck = function(data, func) {
    var socket = this.server.sockets.connected[this.client.id];

    socket.emit('BinaryEventWithNoAck', new Buffer("Binary event", 'binary'));
}



//Client receive this :
51-["BinaryEventWithNoAck",{"_placeholder":true,"num":0}]
//Then, the datas :
[B@5176ade8
//Then nothing else. I lost myself in the stack...
```

Any idea ?

**Comment by nkzawa** [comment]
Umm, sorry I don't get your problem. Could you make it clear? 
Where does the problem actually happen on your code?

**Comment by dimitrilahaye** [comment]
So, Client side, I send an event ("EventAskBinaryEventWithNoAck") with a JSON Object. The Server ask me with another event ("BinaryEventWithNoAck") and the data it sends to the client is a String "Binary event" in binary.
The URI of the manager is :

```java
51-["BinaryEventWithNoAck",{"_placeholder":true,"num":0}]
```
which means that I will receive a binary event (and the int 1, I don't remember what it means).

I receive this data in Manager.java in this method :

```java
    private void ondata(String data) {
        this.decoder.add(data);
    }
```
Then, I receive the binaries datas — [B@5176ade8 — in the following method :

```java
    private void ondata(byte[] data) {
        this.decoder.add(data);
    }
```
then, after that, I receive "pong" event in the onPacket method of the Transport.class, and nothing else.
Normally, i'm supposed to receive the binaries datas, convert them in String and all is ok. And it works like a charm without namespace.

**Comment by nkzawa** [comment]
what do you mean namespace? it doesn't appear so far.

**Comment by dimitrilahaye** [comment]
Namespace is "/public" http://localhost:8080/public
You have this constructor for Socket : public Socket(Manager io, String nap) where nsp is the namespace. I think it is the equivalent of the path in a URI...

In the code, before to get the string "51-["BinaryEventWithNoAck",{"_placeholder":true,"num":0}]" in the on data(String) method of Manager.java, I've also got the string "0/public".

**Comment by nkzawa** [comment]
how did you create a socket on server side?
please remove redundant parts from your code snippets. I can't understand them.

**Comment by dimitrilahaye** [comment]
```javascript
//App.js
var io = require('socket.io')(server);
//...
io.of('/public').on('connection', Server.connect);


//Server.js
Server.connect = function(socket)
{
	socket.on('EventAskBinaryEventWithNoAck', Socket.eventAskBinaryEventWithNoAck);
}


//Socket.js
Socket.binaryMessageWithNoAck = function(data, func)
{
	var socket = this.server.sockets.connected[this.client.id];
	socket.emit("message", new Buffer("Binary message", 'binary'));
}
```

**Comment by nkzawa** [comment]
`var socket = this.server.sockets.connected[this.client.id];`

On this line, you are getting a socket of '/' (default namespace). btw I assume `this.server` is the socket.io server.

`var socket = this.server.of('/public').connected[this.client.id];`

you have to do line above.

**Comment by dimitrilahaye** [comment]
Ok, but what is, on your opinion, the use of this :

```javascript
io.of('/public').on('connection', Server.connect);
```
It is in the App.js file which creates the Node server. It is where I create the two others :

```javascript
var app = require('express')();
var server = require('http').Server(app)
var io = require('socket.io')(server);
var Server = require('./Server');
server.listen(8080);

io.of('/public').on('connection', Server.connect);
io.on('connection', Server.connect);
```

**Comment by nkzawa** [comment]
I don't get why you do so, but it's nothing wrong.
Anyway I'll close the issue since I believe it's not the problem of the lib.

**Comment by dimitrilahaye** [comment]
But... I create the socket with namespace /public there :

```javascript
io.of('/public').on('connection', Server.connect);
```

The method connect() of Server is here :

```javascript
Server.connect = function(socket)
{
//... a lot of socket.on...
	socket.on('EventAskBinaryEventWithNoAck', Socket.eventAskBinaryEventWithNoAck);
} // end of the connect() method.
```

So, the eventAskBinaryEventWithNoAck() of Socket is here :

```javascript
Socket.eventAskBinaryEventWithNoAck = function(data, func)
{
	var socket = this.server.sockets.connected[this.client.id]; //this is NodeJS
	
	socket.emit('BinaryEventWithNoAck', new Buffer("Binary event", 'binary'));
}
```

I don't see why it is not working. Without namespace, there is no matter :-/
