### ISSUE TITLE
Reconnect after EVENT_ERROR

### ISSUE THREAD

**Issue by dimitrilahaye** [nkzawa/socket.io-client.java#99]
Hello !
I just like to know how can I re-try connection after an EVENT_ERROR ?

**Comment by nkzawa** [comment]
It would automatically retry it by default settings. You can explicitly call `connect()` to reconnect.

**Comment by dimitrilahaye** [comment]
Thanks you, call explicitly connect() works like a charm ;-)

**Comment by nkzawa** [comment]
:smiley:
